### ISSUE TITLE
Create numerical filter with brushing

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#10]
The numerical value should be represented in linear gradient and with brushing for the selection of the range.

![jan-24-2017 5-32-44 pm](https://cloud.githubusercontent.com/assets/12292333/22256487/360bf53e-e25b-11e6-8c51-eee48d49ecea.gif)

**Comment by mstreit** [comment]
The gradient should reflect the data distribution. Also, the min/max and filter values should be shown.

**Comment by bikramkawan** [comment]
Current State:
![image](https://cloud.githubusercontent.com/assets/12292333/22422222/96994ffc-e6eb-11e6-8108-be3382d0f970.png)
