### ISSUE TITLE
Hierarchical sorting

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#103]
TO DO:

- [x] Hierarchical sorting

- [x] Filtering  Scenario

- [x] Let user drag the attribute in filter view and trigger the sort 

**Use Case for filtering:**
Add some columns
Filter some data
Sort by any column
Get back the filtered data
The sorting should be same as before.

**Use Case for Hierarchical:**
Assume sorting criteria is ascending.
Sorting hierarchy : US>Status>Gender
Step 1:
![image](https://cloud.githubusercontent.com/assets/12292333/23028401/83985c5c-f467-11e6-83a4-deb2a68b2b35.png)
Step 2 : Filter some data as below:
![image](https://cloud.githubusercontent.com/assets/12292333/23028432/9a7e3c8e-f467-11e6-901f-63fff66569f9.png)
Step 3:
sorted by country	
![image](https://cloud.githubusercontent.com/assets/12292333/23028504/d6dcfdbe-f467-11e6-9e74-a06391ae9013.png)
step 4 :sorted by status
![image](https://cloud.githubusercontent.com/assets/12292333/23028525/e524e6ca-f467-11e6-9f83-8556cf496eda.png)

step 5 : sorted by gender
![image](https://cloud.githubusercontent.com/assets/12292333/23028543/f0e50508-f467-11e6-8f18-e6785ae909d9.png)

Final output:
![image](https://cloud.githubusercontent.com/assets/12292333/23028578/0b22428c-f468-11e6-9b80-f9aa2a1c1334.png)

**Comment by mstreit** [comment]
yes, can be implemented elegantly using a recursive function (https://en.wikipedia.org/wiki/Recursion_(computer_science))

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23106789/06125d30-f6f3-11e6-808a-19a593ebeda1.png)
