### ISSUE TITLE
Update filter view based on sorting criteria from table view.

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#108]
The filter view should be updated based on the sorting criteria from the table view.
![image](https://cloud.githubusercontent.com/assets/12292333/23116927/7c064db2-f74d-11e6-8e69-bdfe13a0e98c.png)
If we select career status as primary sort criteria from table view it should be updated as follow
![image](https://cloud.githubusercontent.com/assets/12292333/23116956/a2d2289e-f74d-11e6-8ba9-8adfc4746cc8.png)

**Comment by bikramkawan** [comment]
There are a couple of confusion for me on how to update filter view based on user click on the header of the column.
Consider the above scenario.
- The column is in the order of figure 1.
- Consider user click on sort icon of career status it will be changed from ASC to DSC. 

- The rest of the column updated based on DSC.

- Now I move the career status on top position in filter view. How will the user know that it is sorted by ASC or DSC? 
- How to maintain the order of the sort hierarchy? Is it just move the currently selected column to the top and shift another column one step down?

**Comment by bikramkawan** [comment]
Current state:
![feb-20-2017 3-26-01 pm](https://cloud.githubusercontent.com/assets/12292333/23128920/f732ffa2-f780-11e6-86ca-9d40cdffdd2d.gif)

**Comment by mstreit** [comment]
Usually this is solved by showing a little icon that indicates the sort direction.

Regarding the order: If the user actively triggers a sort action on one of the columns, it should become the primary one and all others will be shifted down.
