### ISSUE TITLE
Group numerical columns for hierachical sorting 

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#111]
Coming from #103.

Sort hierarchy:
1. age
2. artist name

**Expected**
Considering that we have multiple artists with age = 35, the numerical column must be sorted and grouped. In the second step all artists with age = 35 should be sorted by alphabet.

**Comment by bikramkawan** [comment]
This is what we want right ?
![image](https://cloud.githubusercontent.com/assets/12292333/23136095/6946fbc4-f79b-11e6-958e-5d623b0cf078.png)
