### ISSUE TITLE
Fix tooltip in filter view

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#115]
The tooltip overrides the label within the category:
![image](https://cloud.githubusercontent.com/assets/4129755/23170303/f76127f0-f84e-11e6-9710-d0586219e0ae.png)

The appearance of the tooltips should be improved.

**Comment by mstreit** [comment]
@bikramkawan, this seems to be done, right? If yes, please close the issue. I really don't want to remind you for every issue. So please keep the issues up-to-date.

![image](https://cloud.githubusercontent.com/assets/4129755/23606418/ee08ab44-0260-11e7-81c3-4617bc55e22a.png)

**Comment by bikramkawan** [comment]
Sorry I will have look on other open issue also. This is done.

**Comment by mstreit** [comment]
OK, thx.
