### ISSUE TITLE
Height of histogram bars is incorrect for TCGA data

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#116]
![image](https://cloud.githubusercontent.com/assets/4129755/23170843/f81ff250-f850-11e6-9450-5f82e6af9218.png)

**Comment by mstreit** [comment]
still a problem

![image](https://cloud.githubusercontent.com/assets/4129755/23496832/86afe888-ff20-11e6-8d2f-40400ed9645a.png)

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23524533/60b35cf8-ff8b-11e6-869c-5a59ac2e273d.png)
Entries 476,13,93
If specify minimum height then the entries 13 and 93 makes hard to differentiate.
![image](https://cloud.githubusercontent.com/assets/12292333/23524638/bdb3bbbe-ff8b-11e6-994b-bbd30472fa64.png)

**Comment by mstreit** [comment]
There should not be a minimum size. A histogram should just show the unmodified counts encoded in the length of the bar.
Btw: Why is the label not below the bar as it was already the case?

**Comment by bikramkawan** [comment]
Ok. I have not updated from the master so it is not shown below.

**Comment by mstreit** [comment]
If one of the bars gets too small to be picked, you can still make the transparent pick area bigger than the visible bar.

**Comment by bikramkawan** [comment]
Since the PR https://github.com/Caleydo/mothertable/pull/167 is merged I will closed this issue.
