### ISSUE TITLE
Why is different in data vector and data description for categorical in TCGA datasets ?

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#118]
The value of categorical data in TCGA data is as below 
For example in patient ethnicity.
The vector is stored as numerical 
![image](https://cloud.githubusercontent.com/assets/12292333/23182473/ea09da00-f878-11e6-8c01-6bcce2b58de7.png) 
But the categories is defined in data description as following.
![image](https://cloud.githubusercontent.com/assets/12292333/23182709/cdbe0992-f879-11e6-80ae-5acfa96305dd.png)

In artist data 
For example career status:
the vector is specified as 
![image](https://cloud.githubusercontent.com/assets/12292333/23182902/7f598028-f87a-11e6-8046-426c1743ba37.png)

and also the data description is specified 
![image](https://cloud.githubusercontent.com/assets/12292333/23182948/a27e41c4-f87a-11e6-9453-cca0190c656d.png)

Should not it should be same?

**Comment by mstreit** [comment]
Yes, TCGA data loaded from the HDF packages has a different structure. Obviously, the index of a category is stored that is then further specified in the description. Instead of the label of the category it stores the index of the category as specified in the description.

**Comment by bikramkawan** [comment]
But the vector has unique value of [1,2,3] only, but in the description, it is specified four categories as shown in above figure. Why four instead of 3? Is unknown for missing value ?
