### ISSUE TITLE
Update the tableview after sorting

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#120]
The table view should be updated after the user finishes dragging event in filter view. This is to synchronize the same order in both views.

**Comment by bikramkawan** [comment]
Current state:
The sorting is order derived as in filter view. But the table view is different which is difficult to synchronize the visual representation.
![image](https://cloud.githubusercontent.com/assets/12292333/23258777/0336d8aa-f9ca-11e6-9b24-8f8d17c7a784.png)

So we want to make the table view same as in filter

**Comment by mstreit** [comment]
What do you mean by "make the table view same as in filter"?

**Comment by bikramkawan** [comment]
The table view should be same as filter view order.
It means the column should be in the order of Origin, Gender and Career status

**Comment by mstreit** [comment]
No! This is what we don't want to have. The column order in the table should be independent of the sort order. Otherwise the user would not be able to bring them in a specific order without changing the sorting.

**Comment by bikramkawan** [comment]
But it will be difficult to see the sorting effect on the table view isn't it ?

**Comment by mstreit** [comment]
Yes, but as the user specified the hierarchy on the right he knows exactly what happens.

**Comment by bikramkawan** [comment]
Ok got the point then  I will close this issue.
