### ISSUE TITLE
Intersection between different filter types

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#13]
The filter should perform intersection when we select different types of filter.
For example: If we select the male from one categorical data and US from another categorical data. The result should only display excluding male and US.
[1,2,3,4]- Indices of Male 
[3,4]- Indices of US
The result of intersection should be [3,4].

**Comment by bikramkawan** [comment]
Intersection with Matrix is remaining.

**Comment by mstreit** [comment]
@bikramkawan, is this done now after merging the recent PRs?

**Comment by bikramkawan** [comment]
yes it was done in #84
