### ISSUE TITLE
The sort order not update when click on column header

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#135]
When user click on column header from asc to dsc it is not updating the sort criteria.

**Comment by bikramkawan** [comment]
![feb-24-2017 12-50-09 pm](https://cloud.githubusercontent.com/assets/12292333/23302652/d4bbffe8-fa8f-11e6-9206-7a279aa29def.gif)

**Comment by mstreit** [comment]
Please don't forget to always test it with the larger TCGA datasets - just to make sure that the features work as expected.

**Comment by bikramkawan** [comment]
ok
