### ISSUE TITLE
Change color of gender categories

### ISSUE THREAD

**Issue by alexsb** [Caleydo/mothertable#148]
These are ugly: 
![image](https://cloud.githubusercontent.com/assets/2039375/23413808/25b86404-fd97-11e6-97b8-12e495ae0317.png)

Use a set from color brewer.

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23416053/90136868-fde1-11e6-8058-c430cd5ce4c6.png)

**Comment by mstreit** [comment]
Use same colors for TCGA as in artists.

![image](https://cloud.githubusercontent.com/assets/4129755/23496748/1d32a33c-ff20-11e6-8541-9df58c9ecc3f.png)

**Comment by mijar** [comment]
the gender is OK now, but the rest of the attributes is being assigned same colors as the gender...looks quite confusing then...
![image](https://cloud.githubusercontent.com/assets/7511570/23512687/bdbe9130-ff61-11e6-95f6-6ce23d6ffa2f.png)

**Comment by bikramkawan** [comment]
It should be okay now. I have explicitly defined color based on colorbrewer.
![image](https://cloud.githubusercontent.com/assets/12292333/23579032/84d8f57a-00e4-11e7-9eda-3b8bb183700f.png)

**Comment by mstreit** [comment]
Looks good now.

**Comment by mstreit** [comment]
@bikramkawan, link to PR or commit missing.

**Comment by bikramkawan** [comment]
The PR is linked here.
https://github.com/Caleydo/mothertable/pull/164
