### ISSUE TITLE
Sort histogram bars when sorting by an attribute 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/mothertable#149]
![image](https://cloud.githubusercontent.com/assets/2039375/23414111/0bab4936-fd98-11e6-8b62-eb3317a8399b.png)

Here we're sorting by the number of artists from these countries in the table, but the histogram is still alpha-numeric. The histogram should be sorted in-sync with the table. 

This also applies to numeric data.

**Comment by bikramkawan** [comment]
![mar-01-2017 9-47-24 am](https://cloud.githubusercontent.com/assets/12292333/23452304/20e09bcc-fe64-11e6-9330-7884ab036205.gif)
