### ISSUE TITLE
Remove Block from Main View and Filter

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#15]
When the user clicks on the cross icon, the corresponding block should be removed from main view and filter view.

**Comment by katush** [comment]
- [ ] When the block is added several times to the Main view, check the count and only remove it from filter view after the last instance in Main view is removed

**Comment by bikramkawan** [comment]
Done on this commit
https://github.com/Caleydo/mothertable/commit/65438acbb711d012dad27ee873cb20323ca9db6b
