### ISSUE TITLE
Create histogram for matrices

### ISSUE THREAD

**Issue by alexsb** [Caleydo/mothertable#151]
Numerical matrices don't have a histogram right now: 

![image](https://cloud.githubusercontent.com/assets/2039375/23414806/622535cc-fd9a-11e6-892b-b06cfd493939.png)

Create a histogram for all values, just as with individual vectors.

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23579096/1072a986-00e6-11e7-972a-13360c6ca958.png)

**Comment by mstreit** [comment]
@bikramkawan, done and already merged, right?

**Comment by bikramkawan** [comment]
It's merged already.So I close here.
