### ISSUE TITLE
Render a histogram for numerical vectors

### ISSUE THREAD

**Issue by alexsb** [Caleydo/mothertable#152]
Right now, this uses color to encode the number of items in a bin: 

![image](https://cloud.githubusercontent.com/assets/2039375/23414878/a422a770-fd9a-11e6-945e-f6a2385e10e0.png)

This is not a good choice, since the color doesn't match with a color used in the table (not even dark vs light matches).

Use a plain histogram instead. If you use color to encode the data in the table, use the same color in the histogram bars. Otherwise make the histogram monochrome.

**Comment by bikramkawan** [comment]
Looks nice when we have large dataset
![image](https://cloud.githubusercontent.com/assets/12292333/23435860/d51776a8-fe08-11e6-9250-b71f17cbc2b4.png)

**Comment by alexsb** [comment]
Throw in a light frame for the bars just to counter-act white on white please.

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23436305/4e03ae32-fe0a-11e6-9fa6-0c2ec52ba2c7.png)

**Comment by alexsb** [comment]
That looks good. Question: are you encoding the frequency of the bin with color (looks like it) or the position along the range? I think it should be the latter.

**Comment by bikramkawan** [comment]
This is the question I was about to the post here. Currently, I encode color with the bin entries. The range you mean the min-max value of the data ?

**Comment by alexsb** [comment]
yes. The color coding here should match what you show in the data. I'd expect this to be a gradient then.

**Comment by bikramkawan** [comment]
The data in bins are unevenly distributed in histogram lets say we have three bins as here:
![image](https://cloud.githubusercontent.com/assets/12292333/23454212/ea91327c-fe6b-11e6-8516-2ddc6e49c7ea.png)
First bin: 6 entries  with values [7,8,6,8,7,8]
Second bin: 4 entries with values [12,10,12,12]
Third bin: 2 entries with values [33,25]
How can we make gradient based on this situation?

The another way we can achieve the gradient is as below when we provide each bin for each value with the same width, and the frequency should correspond the height of the width.
![image](https://cloud.githubusercontent.com/assets/12292333/23454512/c422d32e-fe6c-11e6-911d-448569893f20.png)

**Comment by bikramkawan** [comment]
Does it make sense  now ?
![image](https://cloud.githubusercontent.com/assets/12292333/23523626/fe7b8db0-ff87-11e6-8bc9-e133eac5301f.png)

**Comment by mstreit** [comment]
Yes, looks good now. The color should match the color to the color shown in the table. Also use the red that Alex suggested.

Btw: You can make the handles (black triangles) a bit smaller and center the text horizontally below the triangle (without overlap).

**Comment by bikramkawan** [comment]
I am updating here #35 also in this issue.
![mar-04-2017 2-15-23 pm](https://cloud.githubusercontent.com/assets/12292333/23579054/220dd4aa-00e5-11e7-9e51-0acf8549238c.gif)
Thanks alot @thinkh for this brushing help.:)

**Comment by thinkh** [comment]
Looks good now. Only one small thing: Could you update the numbers below the frame already on drag and not after mouse up?

**Comment by thinkh** [comment]
This is already merged with the master.
