### ISSUE TITLE
Should we label histogram bars below instead of in the bars?

### ISSUE THREAD

**Issue by alexsb** [Caleydo/mothertable#154]
Labeling inside a bar has a couple of drawbacks: 

![image](https://cloud.githubusercontent.com/assets/2039375/23416129/cbd4d532-fd9e-11e6-90d3-16e8651cda60.png)

 * It's hard to guarantee a sufficient contrast of label vs background
 * bars could be short, so the label could be partially on white background and partially on the label. 

Hence, I suggest to put the labels below the bar. Downside: needs more space. 

Opinions?

**Comment by mstreit** [comment]
Yes, I agree with your suggestion.

**Comment by bikramkawan** [comment]
Looks cleaner more :)

![image](https://cloud.githubusercontent.com/assets/12292333/23434505/04aff2bc-fe06-11e6-8d06-dbbb3e55963d.png)
