### ISSUE TITLE
Split multiform based on range

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#157]
Currently multiform is rendered as a single instance.For this we are not using multiform grid . If we have the array of range element, it should split as in the figure. 
![image](https://cloud.githubusercontent.com/assets/12292333/23459764/2c08f062-fe82-11e6-8920-ed232a6823d5.png)

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23471424/8d756c00-fea9-11e6-8d29-e4b1dace5b17.png)

**Comment by mstreit** [comment]
Related to #65

**Comment by mstreit** [comment]
@bikramkawan, what is the status here? According to the screenshot you aggregate the lower part of numerical vectors. But what is needed to fully solve the issue?

**Comment by bikramkawan** [comment]
The idea is to use one multiform for each range (array of the index ) obtained from sorting.  For further we can discuss on meeting.

**Comment by bikramkawan** [comment]
![mar-05-2017 10-25-04 pm](https://cloud.githubusercontent.com/assets/12292333/23591586/b8c0e1e0-01f2-11e7-8c17-1750c134113b.gif)
This is the first step. There is some work related to the multiform resizing.

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23660309/47c43728-0349-11e7-9574-be657cef48d3.png)

**Comment by mstreit** [comment]
OK, and what is missing now to finish the brushing?

**Comment by bikramkawan** [comment]
I am trying to assign the height and width based on 
For now I am working on the below ticket
https://github.com/Caleydo/mothertable/issues/170
