### ISSUE TITLE
Create String filter 

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#16]
If the attribute is String type. The user should be able to filter the data with string search pattern

**Comment by mstreit** [comment]
Please provide a bit more information so that everyone knows what the issue is about.

**Comment by bikramkawan** [comment]
Current State: Text with Brushing
![image](https://cloud.githubusercontent.com/assets/12292333/22422063/c2101130-e6ea-11e6-9dcd-3d1e4c013652.png)
