### ISSUE TITLE
Filtered categories should appear in gray in filter dialog

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#163]
![image](https://cloud.githubusercontent.com/assets/4129755/23547426/65181cf2-0003-11e7-9514-6536327dc6a8.png)

**Comment by mstreit** [comment]
I've discussed with Bikram that we don't need PRs for changing colors, labels etc. Just push it.

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23551574/a61c1f6e-0017-11e7-811c-c3a3ffafee7e.png)

**Comment by mstreit** [comment]
Yes. Also use the same gray for the category name below.

**Comment by bikramkawan** [comment]
ok

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23579079/a7e47f48-00e5-11e7-9eb2-3ecc4fff26f7.png)

**Comment by mstreit** [comment]
@bikramkawan, the link to the corresponding PR or commit is missing.

**Comment by bikramkawan** [comment]
It is included in this PR
https://github.com/Caleydo/mothertable/pull/167
