### ISSUE TITLE
Make toolbar on every multiform

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#169]
Currently, multiple instances of multiform are created based on the hierarchical sorting indices. Do we make the toolbar for switching visualization for all instances of multiform?

**Comment by mijar** [comment]
I would say the toolbar should only refer to the whole column, not multiform instances...IMHO the user would like to have the content of the column consistent...

**Comment by mstreit** [comment]
In general I agree. The question is what to do if multiple visualizations are already mixed in the column because of the aggregation (e.g., lower part of table shown as boxplot while upper part is shown in more detail as heatmap.)
