### ISSUE TITLE
Specify min/max/preferred height/width of multiform blocks depending of type

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#170]
Currently multiform takes all the space which are available. Specify the minimum space for the multiform depending on the content.This is important since we are creating multiple instances of multiform.
Below is the case if we do not restrict the multiform size.
![image](https://cloud.githubusercontent.com/assets/12292333/23602766/5449fa5c-0252-11e7-9053-8c7ed999a6d5.png)

**Comment by mstreit** [comment]
Also set a max height of rows.

**Comment by mstreit** [comment]
Who is taking care of this?

**Comment by mstreit** [comment]
I suggest to apply a max height that still allows us to show text within the row (if applicable).

**Comment by bikramkawan** [comment]
Currently I am taking care of this marc.

**Comment by thinkh** [comment]
Related tickets: 
* https://github.com/Caleydo/mothertable/issues/65
* https://github.com/Caleydo/mothertable/issues/36

**Comment by bikramkawan** [comment]
Consider we have 50 px for multiform. We can render bar and heatmap. But switching the different visualization, we need see how it can be handled.
![mar-07-2017 2-06-25 pm](https://cloud.githubusercontent.com/assets/12292333/23657805/27758980-0340-11e7-926c-31ef6d4eb795.gif)

**Comment by mstreit** [comment]
If the user switches to a multiform vis that needs more space, we need to give it the minimum size it needs. The rest of the multiforms need to be shrinked accordingly. Or is there something wrong with this strategy?

**Comment by mstreit** [comment]
see also #192

**Comment by bikramkawan** [comment]
Minimum Space Requirements per data element	
<pre>VisType	    height	         width
Barplot	     2px	          20px
String	     8px	          20px
Heatmap	     2px	          20px
BarPlot	     20px	          20px 
</pre>

**Comment by mstreit** [comment]
barplot is listed twice?

**Comment by sgratzl** [comment]
I guess the height is per row and the width in total?

that leads to a followup question: why is the width of a 2D heatmap not dependent on the number of columns shown?

**Comment by bikramkawan** [comment]
Yes, the height is per row.
For 2D heatmap 2px*2px for one data element.

**Comment by mstreit** [comment]
@bikramkawan, please update the list above accordingly

**Comment by bikramkawan** [comment]
I have updated the maximum space requirements. You can suggest the preferred space. This is for not using the  whole space if we have less number of items to fill.

**Comment by mstreit** [comment]
I think a boxplot does not need 40px. 15px should be sufficient.

**Comment by mstreit** [comment]
what about the boxplot?

**Comment by bikramkawan** [comment]
Typo error

**Comment by mstreit** [comment]
I still don't see a boxplot in the list.

**Comment by bikramkawan** [comment]
Updated

**Comment by mstreit** [comment]
OK. But what about a histogram (for summarizing numerical data) and a bar charts (for summarizing categorical data)?

**Comment by bikramkawan** [comment]
It will be hard to see the histogram in too little space, is not it? But still, we can render it.

**Comment by mstreit** [comment]
Isn't that why we define a minimum height?

**Comment by bikramkawan** [comment]
Yes

**Comment by sgratzl** [comment]
> Histogram	10px	20px

I don't get this line, why is the minimum height of a histogram: `10px * number of contained items`?

**Comment by mstreit** [comment]
yes, a histogram and a bar chart has a fixed height that is independent of the #items. @bikramkawan, please update the table accordingly.

**Comment by mstreit** [comment]
@bikramkawan, where in the code do you plan to specify the min/preferred/max width/height?

**Comment by bikramkawan** [comment]
Yes, that is independent of items. That is the maximum height of the bins which contains a maximum number of items.

**Comment by sgratzl** [comment]
> Yes, that is independent of items. That is the maximum height of the bins which contains a maximum number of items.

So, according to your definition, the following two histograms will have two different minimum heights, right?

```
X
X       
X X    X X
X X   XXXX  
XXXX  XXXX
```

**Comment by mstreit** [comment]
Bar charts and histograms should have a fixed height (as in the filter view).

**Comment by bikramkawan** [comment]
In this case, the maximum height of multiform for histogram will be the dimension specified above and the histogram will be rendered accordingly by scaling function I guess.

**Comment by mstreit** [comment]
According to #37 there are already some dummy values set. You probably just need to update them.

**Comment by mstreit** [comment]
@bikramkawan, this is done, right?

**Comment by mstreit** [comment]
Please post a link to the LOC where the min/max values are defined before closing the issue.

**Comment by bikramkawan** [comment]
No I am still working on this with multiple multiform. And what do you mean by LOC ?

**Comment by mstreit** [comment]
LoC = Line of Code

**Comment by bikramkawan** [comment]
The splitting multiform has performance issue for the TCGA dataset (large dataset).
Also, there is the minor issue regarding the rendering the multiform in the browser. The behavior of rendering can be seen from the below figure.The white lines space are the rendering from the browser because of too many dom elements close to each other. In the present scenario, I have not added the toolbar for changing visualization for each multiform. Adding this will introduce more complex on performance.

@thinkh and I discussed on one improvement regarding the performance issue. If there are the same visualization for certain ranges instead of splitting we can replace by single multiform. But doing this it will restrict on changing the type of visualization.But we are not sure how much will it scale.

So this is blocking from moving to next step i.e. aggregation and different visualization for each aggregation level.

![mar-10-2017 1-18-28 pm](https://cloud.githubusercontent.com/assets/12292333/23795230/b5fd17f8-0594-11e7-8ab9-70c18440469a.gif)

**Comment by sgratzl** [comment]
out of curiosity: how many multiforms are created per column in this screencast and why?

**Comment by bikramkawan** [comment]
When we add numerical data it's almost the same size of data. It means for now around 580. This is because from the hierarchical sorting.

**Comment by bikramkawan** [comment]
Since it is merged with #157 I will close here.
