### ISSUE TITLE
Maintain hierarchical sorting after dragging and adding new column 

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#171]
Information flow of column manager
1. Filter Data
2. Sorting 
3. Dragging selection

**Comment by mstreit** [comment]
Is this issue still valid? If yes, please make the description clearer. I don't know what the problem is.

**Comment by mstreit** [comment]
@bikramkawan, ping!

**Comment by bikramkawan** [comment]
Sorry forgot about this. This is related to #54.

**Comment by mstreit** [comment]
Why is it related to #54? We don't have any brushing at the moment.

**Comment by bikramkawan** [comment]
yes. But this issue is related to #54 because it should also listen to the filter trigger event. I created this some days before for future reference not to forgot.

**Comment by bikramkawan** [comment]
Since #54 is merged I will close this.
