### ISSUE TITLE
When resizing the window the table header should not get detached from the table

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#172]
![image](https://cloud.githubusercontent.com/assets/4129755/23605699/05c8e7ec-025e-11e7-9128-2df8a620b887.png)

**Comment by thinkh** [comment]
I think this is related to @katush resize functionality. Correct, @katush?

**Comment by mstreit** [comment]
Seems to be fixed with latest changes.

![image](https://cloud.githubusercontent.com/assets/4129755/23624980/e493839e-02a7-11e7-902b-ba669e609fd7.png)

**Comment by mstreit** [comment]
@thinkh, I assume that you are going to address this as well when you work on the layout, right?

**Comment by thinkh** [comment]
Yes, but only regarding the width. @bikramkawan is working on the height.

**Comment by thinkh** [comment]
For the width it's fixed with this commit: https://github.com/Caleydo/mothertable/pull/197/commits/77b45dd34d4621a94900c95bd3db710baef47607

This will trigger the columnManager.relayout() every 250 ms when resizing the window.

**Comment by mstreit** [comment]
Works with the recent height changes from @bikramkawan.
