### ISSUE TITLE
Adaptive labels in multiform visualizations

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#173]
If we filter down the table to contain a very few items, we should show category labels and numerical values in the table (if the row height is big enough). 

![image](https://cloud.githubusercontent.com/assets/4129755/23605848/96b96e3e-025e-11e7-898d-1f403dc21b3c.png)

**Comment by mstreit** [comment]
What is missing to complete this issue?

**Comment by katush** [comment]
There seems to be a bug in mosaic labels, that I was not able to fix. Holger is looking into that today.

**Comment by mstreit** [comment]
OK. Related to #224.

**Comment by mstreit** [comment]
Works.
