### ISSUE TITLE
Numerical columns should be shown as bar charts by default

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#175]
Only switch back to heatmap when the column gets very little space assigned.

**Comment by thinkh** [comment]
What should be the coloring for the bar chart?

![taggle_barcharts](https://cloud.githubusercontent.com/assets/5851088/23624204/3f2ad8f0-02a5-11e7-84c6-57689afbe080.png)

**Comment by mstreit** [comment]
We could use a double encoding with the same color map as in the filter view (white-dark red). @alexsb, what do you think?
![image](https://cloud.githubusercontent.com/assets/4129755/23625093/42176e68-02a8-11e7-9fe5-8af9f120a944.png)

**Comment by alexsb** [comment]
If we use color then yes, the color should be used consistently. 

However, this is already very colorful, so this might be an opportunity to go gray ;)

**Comment by mstreit** [comment]
Yes, the black is bit too hard for my taste.

**Comment by thinkh** [comment]
The black bar chart is changed with grey bars.

![taggle_barchart-color](https://cloud.githubusercontent.com/assets/5851088/23657473/95d8ad00-033e-11e7-9d88-c898e7ca989a.png)
