### ISSUE TITLE
Let user change column order interactively via drag and drop

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#176]
Related to #106.

**Comment by thinkh** [comment]
This works already!

![taggle_reorder-columns](https://cloud.githubusercontent.com/assets/5851088/23618595/186ac586-0291-11e7-90e3-b0a99f71ae1c.gif)

@mstreit Please re-open this issue if think there is something missing.

**Comment by mstreit** [comment]
Oh OK, I didn't know that. Great.
