### ISSUE TITLE
Apply categorical filter also when clicking on label below histogram bar

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#180]

**Comment by thinkh** [comment]
![taggle_click-on-categorynames](https://cloud.githubusercontent.com/assets/5851088/23625086/3b89fa48-02a8-11e7-84e5-19ff6a042a73.gif)

**Comment by thinkh** [comment]
Ah I see that there is still a bug

**Comment by thinkh** [comment]
Fixed. See PR #187 

![taggle_click-on-categorynames2](https://cloud.githubusercontent.com/assets/5851088/23647156/9bdec952-0314-11e7-9ad7-8f30770b5885.gif)
