### ISSUE TITLE
Remove border around histogram but keep min and max delimiter line

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#185]
![image](https://cloud.githubusercontent.com/assets/4129755/23625261/ded4cc00-02a8-11e7-8bc4-f5fadf8f356f.png)

Also add the triangles again so that users see that they can drag the line.

**Comment by mstreit** [comment]
But I think you can keep the baseline as well. So maybe just remove the line at the top.

**Comment by mstreit** [comment]
The histogram should have the same style as the histograms for matrices.

**Comment by bikramkawan** [comment]
Since we have no filtering in matrix does it make sense to have border lines?
![mar-06-2017 9-30-40 pm](https://cloud.githubusercontent.com/assets/12292333/23628358/4e03a3ac-02b4-11e7-8cbf-5f4273b879ef.gif)

**Comment by mstreit** [comment]
Looks good. The baseline can be light gray too, going from the min value to the max value. The min/max vertical filter lines can remain black.
