### ISSUE TITLE
Configure setup based on URL hash

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#189]
To avoid clicking initial columns over and over again, we should support a configuration that can be loaded based on the URL hash (e.g. something like that: http://localhost:8080/#age+firstalbum).

**Comment by mstreit** [comment]
This is important because it will save us all a lot of time during testing.

**Comment by thinkh** [comment]
Yes, I'm going to work on this now.

**Comment by mstreit** [comment]
@think, nice! Should we create a placeholder issue where we collect some example URLs?

**Comment by thinkh** [comment]
Yes, good idea.

**Comment by thinkh** [comment]
Closed, because the PR is merged.
