### ISSUE TITLE
Remove the block from Main View

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#19]
Empty selectiion

![image](https://cloud.githubusercontent.com/assets/12292333/22333274/88e35ac4-e3d5-11e6-90c8-2fdf5283f8e0.png)
If we select as in filter dialog exclude female , inactive and artists starting with G then we have empty selection as below.
![image](https://cloud.githubusercontent.com/assets/12292333/22333257/6e08b0d2-e3d5-11e6-9a79-37a392b9e622.png)
Remove all blocks from filter and main view.  Or what should we do ?

**Comment by mijar** [comment]
The selected filter setup is a query, we wanted to see e.g. "how many people fulfill this criteria in our dataset" and thus the result of 0 rows is a correct result. It is not neccessary to remove the block, we will just leave the header here so the users know what is their setup.
