### ISSUE TITLE
Add label/ID vectors for TCGA data

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#195]
At the moment it's not possible to add gene symbols or sample IDs as a column.

**Comment by sgratzl** [comment]
matrices have the `.rows()` and `.cols()` method
tables/vector the `.names()` method

the return the column/row identifier

**Comment by mstreit** [comment]
OK, so we already have them but the dataset dropdown does not offer the labels as an option. @bikramkawan, can you please add a label vector for TCGA data? In the TCGA dataset we can use the Identifiers for the label column. It should look similar to the artists use case where the dataset dropdown offers a 'artist' entry that adds a label column.

**Comment by bikramkawan** [comment]
Ok I will have a look into this @mstreit

**Comment by bikramkawan** [comment]
By using the data.names();
For artist:
![image](https://cloud.githubusercontent.com/assets/12292333/23905617/e791a4b6-08cb-11e7-8c5a-f7981aa2a893.png)

But in TCGA I get errors like this.
![image](https://cloud.githubusercontent.com/assets/12292333/23905642/fe9295c6-08cb-11e7-8d11-3652bd32808e.png)

**Comment by bikramkawan** [comment]
Any hints here @sgratzl ?

**Comment by sgratzl** [comment]
fixed as part of https://github.com/phovea/phovea_data_hdf/pull/9

**Comment by bikramkawan** [comment]
Thanks it worked. How do I create TableVector based on these ids?

**Comment by mstreit** [comment]
@sgratzl mentioned the asVector() function yesterday.

**Comment by bikramkawan** [comment]
The vectors are fine when IDs are added for TCGA. The rows are not same for all matrix and do not correspondence to the ids of TCGA. As in artist dataset, if the idtype is artist the row is 12. For TCGA, the idtype is TCGA_SAMPLE  and the length of vectors data are 582 and but the matrix is different. Some of the matrices have rows 153, and some are 538. If the rows of the matrix are not the same size as of vectors data for the same idtype how to establish the relation of matrix with other vector data. 
![mar-15-2017 10-45-50 pm](https://cloud.githubusercontent.com/assets/12292333/23972615/c4ea546e-09d2-11e7-9f06-c289a4e7258d.gif)

**Comment by mstreit** [comment]
yes, this is what issue #117 is about. the solution will be to make the vectors the same length by building the union of all IDs in all possible columns - but this is unrelated of this issue.

**Comment by mstreit** [comment]
What you show in the video looks fine. You can make a PR for it. The missing ID issue must be  handled in a separate change.

**Comment by thinkh** [comment]
PR is merged -> Closed
