### ISSUE TITLE
Space-filling columns if possible

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#196]
The columns are not space-filling in the width anymore.

![taggle_columns-not-space-filling](https://cloud.githubusercontent.com/assets/5851088/23677075/06ba5862-037f-11e7-89f1-af5919428fde.png)

**Comment by alexsb** [comment]
I would argue that space filling is not a goal, but that the columns should have a width dependent on the content they show. Probably less than 1/3 of what we see here.

**Comment by mstreit** [comment]
Yes, there will be a min/max/preferred size for each column type (see #37). The min width will be much less than in the screenshot shown above. So if there are only a few columns, which don't use the available space, that's of course fine. The space filling refers to the case where columns would grow over the space when using the preferred width. In this case, they will be first shrunk to the min width and then further aggregated - if possible.

**Comment by thinkh** [comment]
@alexsb Please see the PR https://github.com/Caleydo/mothertable/issues/197

Btw. at the moment I handle the preferred size as maximum size. Because a column can only grow/shrink between minimum and maximum (preferred) size.

**Comment by mstreit** [comment]
@thinkh, thanks! Do you think we need a differentiation between max and preferred size?

**Comment by thinkh** [comment]
No, I was thinking of renaming preferred size to maxSize in the code. It would be much clearer.

**Comment by bikramkawan** [comment]
@mstreit I am also thinking that we only need min and preferred size while writing down the excel

**Comment by mstreit** [comment]
OK, then let's just differentiate between min and max size. Initially we add columns using the max size of course.

**Comment by thinkh** [comment]
OK, I'll rename the variables in the code.
