### ISSUE TITLE
TCGA matrices are white only

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#203]
### Steps to reproduce

1. Add any of the TCGA matrices

### Observed behavior
* The heatmap is white. If I select RPPA, I can select cells though. 

### Expected behavior
* Colored heat map

I assume that this is a problem related to a missing color scale for the TCGA matrices. 
@bikramkawan, can you please check what's the issue here? The heatmaps are supposed to use the same white-red color mapping as the filter histograms.

**Comment by mstreit** [comment]
It's not just the color map. This is the error:

```
Uncaught (in promise) TypeError: Cannot read property 'dataView' of undefined
    at SortEventHandler.<anonymous> (SortEventHandler.ts:81)
    at step (tslib.es6.js:91)
    at Object.next (tslib.es6.js:72)
    at tslib.es6.js:65
    at Object.__awaiter [as a] (tslib.es6.js:61)
    at SortEventHandler.sortByMe (SortEventHandler.ts:80)
    at ColumnManager.<anonymous> (ColumnManager.ts:149)
    at step (tslib.es6.js:91)
    at Object.next (tslib.es6.js:72)
    at tslib.es6.js:65
(anonymous) @ SortEventHandler.ts:81
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
(anonymous) @ tslib.es6.js:65
__awaiter @ tslib.es6.js:61
SortEventHandler.sortByMe @ SortEventHandler.ts:80
(anonymous) @ ColumnManager.ts:149
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
(anonymous) @ tslib.es6.js:65
__awaiter @ tslib.es6.js:61
ColumnManager.updateSort @ ColumnManager.ts:144
(anonymous) @ ColumnManager.ts:94
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
fulfilled @ tslib.es6.js:62
data:1 GET http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Mrna-Seq/data?format=png&range=&format_min=-19.9691066742&format_max=0 500 (INTERNAL SERVER ERROR)
```

**Comment by mstreit** [comment]
This is a problem with the toImage feature on the server:
```
api_1  | 22:42:55 ERROR phovea_server.dataset_api: Exception on /matrix/tcgaGbm20140416Mrna-Seq/data [GET]
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1  |     response = self.full_dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1  |     rv = self.handle_user_exception(e)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1  |     reraise(exc_type, exc_value, tb)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
api_1  |     rv = self.dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
api_1  |     return self.view_functions[rule.endpoint](**req.view_args)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 176, in data_gen
api_1  |     return formatter(d, r, args=ns.request.args)
api_1  |   File "phovea_server/phovea_server/plugin.py", line 46, in __call__
api_1  |     v = m(*args, **kwargs)
api_1  |   File "phovea_server/phovea_server/dataset_specific.py", line 110, in format_image
api_1  |     img = scipy.misc.toimage(d, cmin=cmin, cmax=cmax, pal=_color_palette(args.get('format_palette', None)))
api_1  | AttributeError: 'module' object has no attribute 'toimage'
```

**Comment by sgratzl** [comment]
see also https://github.com/phovea/phovea_server/issues/16

**Comment by bikramkawan** [comment]
Our color range is ['#fff5f0', '#67000d']. So I donot know how to fix if the color is only from #00000 to #111111 .

**Comment by thinkh** [comment]
In my local setup with the respective links for the requests:

Attribute | Request 1 | Request 2 | Texture rendered
--------- | ---------- | ---------- | -----------------
Methylation | [successful](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Methylation/data?format=png&range=&format_min=-0.8960109353&format_max=0) | [successful](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Methylation/data?format=png&range=(0%3A123)%2C(0%3A8293)&format_min=-0.8960109353&format_max=0) | no
MicroRNA | [sucessful](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Microrna/data?format=png&range=&format_min=-7.7598257065&format_max=0) | [sucessful](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Microrna/data?format=png&range=(0%3A565)%2C(0%3A150)&format_min=-7.7598257065&format_max=0) | no
mRNA | [successful](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Mrna/data?format=png&range=&format_min=2.1966059208&format_max=14.4421348572) | [sucessful](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Mrna/data?format=png&range=(0%3A538)%2C(0%3A12042)&format_min=2.1966059208&format_max=14.4421348572) | no
mRNA-seq | [sucessful](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Mrna-Seq/data?format=png&range=&format_min=-19.9691066742&format_max=0) | [error 500](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Mrna-Seq/data?format=png&range=(0%3A153)%2C(0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C17%3A14570%2C14569%2C14571%2C14572%3A18214)&format_min=-19.9691066742&format_max=0) | no
RPPA | [successful](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Rppa/data?format=png&range=&format_min=-6.9338788986&format_max=0) | [error 500](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Rppa/data?format=png&range=(0%3A214)%2C(0%3A2%2C1%2C1%2C1%2C5%3A10%2C9%2C11%2C12%3A15%2C14%2C14%2C17%3A23%2C22%2C24%2C25%3A28%2C27%2C29%2C30%3A40%2C39%2C41%2C41%2C43%2C44%3A53%2C52%2C52%2C52%2C56%2C56%2C58%3A62%2C61%2C63%2C64%3A67%2C66%2C66%2C69%2C69%2C71%2C71%2C73%3A86%2C85%2C87%2C88%3A104%2C103%2C103%2C106%3A116%2C115%2C117%2C117%2C117%2C120%3A130%2C129%2C129%2C132%3A135%2C134%2C136%2C137%3A145%2C144%2C146%2C146%2C148%2C149%3A153%2C152%2C154%2C155%3A160%2C159%2C161%2C162%2C162%2C162%2C165%2C165%2C167%3A169%2C168%2C170)&format_min=-6.9338788986&format_max=0) | no

**Comment by sgratzl** [comment]
[error 500](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Mrna-Seq/data?format=png&range=(0%3A153)%2C(0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C17%3A14570%2C14569%2C14571%2C14572%3A18214)&format_min=-19.9691066742&format_max=0) 

range = `(0:153),(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17:14570,14569,14571,14572:18214)`
server error: `IndexError: Selection lists cannot have repeated values` - for which I agree

[error 500](http://localhost:8080/api/dataset/matrix/tcgaGbm20140416Rppa/data?format=png&range=(0%3A214)%2C(0%3A2%2C1%2C1%2C1%2C5%3A10%2C9%2C11%2C12%3A15%2C14%2C14%2C17%3A23%2C22%2C24%2C25%3A28%2C27%2C29%2C30%3A40%2C39%2C41%2C41%2C43%2C44%3A53%2C52%2C52%2C52%2C56%2C56%2C58%3A62%2C61%2C63%2C64%3A67%2C66%2C66%2C69%2C69%2C71%2C71%2C73%3A86%2C85%2C87%2C88%3A104%2C103%2C103%2C106%3A116%2C115%2C117%2C117%2C117%2C120%3A130%2C129%2C129%2C132%3A135%2C134%2C136%2C137%3A145%2C144%2C146%2C146%2C148%2C149%3A153%2C152%2C154%2C155%3A160%2C159%2C161%2C162%2C162%2C162%2C165%2C165%2C167%3A169%2C168%2C170)&format_min=-6.9338788986&format_max=0) 
range = `(0:214),(0:2,1,1,1,5:10,9,11,12:15,14,14,17:23,22,24,25:28,27,29,30:40,39,41,41,43,44:53,52,52,52,56,56,58:62,61,63,64:67,66,66,69,69,71,71,73:86,85,87,88:104,103,103,106:116,115,117,117,117,120:130,129,129,132:135,134,136,137:145,144,146,146,148,149:153,152,154,155:160,159,161,162,162,162,165,165,167:169,168,170)`
same problem

**Comment by thinkh** [comment]
@bikramkawan Could you please check if these duplications are caused by the range split/merge from your hierarchical sorting?

**Comment by bikramkawan** [comment]
@thinkh see here 
https://github.com/Caleydo/mothertable/pull/205

**Comment by mstreit** [comment]
@bikramkawan, why is #205 relevant for this problem?

**Comment by bikramkawan** [comment]
I see the error on scaling because in previous one I filtered vectors to calculate datapoints.

**Comment by mstreit** [comment]
but what has the scaling to do with the filtering?

**Comment by bikramkawan** [comment]
filtering here means I was considering only the length of data from vectors. 
If matrix is added in the first, i have to wait for other vectors to know the data elements. It was bug while I wrote that.

**Comment by mstreit** [comment]
aha, ok. but is #205 supposed to finally solve this issue? because this is not the case when I tested it now.

**Comment by bikramkawan** [comment]
I tested in my machine by adding matrices it worked for me.

**Comment by mstreit** [comment]
@thinkh, can you confirm this please?

**Comment by mstreit** [comment]
the problem was caused by an old local server api build. `docker-compose build api' solved my issue.
