### ISSUE TITLE
Wrong scaling for initially added matrix 

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#207]
### Steps to reproduce

1. Add a matrix to the setup

### Observed behavior

![taggle_wrong-matrix-size](https://cloud.githubusercontent.com/assets/5851088/23758715/e86a7c80-04ea-11e7-8015-ad2e8cb5038d.gif)

### Expected behavior
* The matrix should have the correct scaline right from the beginning.

**Comment by mstreit** [comment]
Fixed in latest master.
