### ISSUE TITLE
Selected visualizations are discarded when adding a column

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#210]
### Steps to reproduce

1. Add a column
2. Switch the visualization in the toolbar of the column
3. Add another column

### Observed behavior

* The visualization type is restored to its default

![taggle_replace-multiforms](https://cloud.githubusercontent.com/assets/5851088/23761133/0fa429e8-04f2-11e7-833d-84656a91fc19.gif)

### Expected behavior

* Keep the selected visualization from the user OR even better do not replace the multiform when adding a new column, but only rescale it (if necessary)

**Comment by thinkh** [comment]
@bikramkawan Could you please have a look into that tomorrow? Maybe you can fix that already while working #157?

**Comment by bikramkawan** [comment]
Ok I will finish 157 first and I can take over this.

**Comment by thinkh** [comment]
Sure. Thanks. 👍

**Comment by bikramkawan** [comment]
This is the approach for single multiform and the same logic will be applied once https://github.com/Caleydo/mothertable/pull/177  is fixed.
![mar-10-2017 12-18-58 am](https://cloud.githubusercontent.com/assets/12292333/23775113/5226bcb0-0527-11e7-89d0-06adf99d709c.gif)

**Comment by bikramkawan** [comment]
I will close this since it is merged

**Comment by bikramkawan** [comment]
It was broken after multiform. So I reopen again.

**Comment by mstreit** [comment]
What means "after multiform"?

**Comment by bikramkawan** [comment]
It's after I reimplemented sorting and stratification it is broken.
