### ISSUE TITLE
Create logic that switches to visualization based on the given space - "Magic box"

### ISSUE THREAD

**Issue by katush** [Caleydo/mothertable#212]
Create Magic Box
Create a VisManager class that will contain the logic of assigning visualizations to multiform

- should contain method `assignVis` that takes multiform and its size as parameters and switches the multiform to correct visualization 
- this method should be called in `ColumnManager`'s `relayout` method when the scaling is applied
- the logic should take into account (in this order):
1. user selected vis (overrides everything) and the table has to adjust according to this
2. initial = preferred vis forgiven data type if the space allows it
3. if the space requirements for multiform do not allow for  initial vis (https://docs.google.com/spreadsheets/d/1q9XLe2LacuuQYAaJ_ewj51do-UX_AhmeZHF8YEoS_6g/edit#gid=432263522), aggregation vis is assigned

RULES:
--------------------------------------------------------------------------------------------
- categorical data is replaced by mosaic plot if the height is too small
- string should be replaced by "blurred" empty vis 
- barplot is replaced by heatmap if the width is too small and then by boxplot if height is too small
 -> exception - barplot does not have to be replaced immediately when the row size is below 1px

**Comment by mstreit** [comment]
@katush, can you please summarize the rules that you plan to apply for the magic box?

**Comment by mstreit** [comment]
First, you could start with numerical columns:
- switch from bar to color encoding if the width of the column is below a certain threshold
- switch from bar renderer to histogram and finally box plot if height is below a certain threshold

**Comment by mstreit** [comment]
Also, switch to mosaic plot for sorted categorical data multiforms.

**Comment by mstreit** [comment]
Remaining issues are/will be reflected in separate issues.
