### ISSUE TITLE
Reimplement sorting and stratification

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#214]
* The whole dataset will be sorted hierarchically according to all filters
* Stratification will only apply until we reach either a numerical or string column -> after that the number of stratifications will stay the same

Example for multiform rendering:
1. career status (categorical) -> 1 multiform with 2 stratifications/categories
2. studio albums (numerical) -> 2 multiforms (1 for each career status category)
3. gender (categorical) ->2 multiforms (1 for each career status category)

Related to #157 #170

**Comment by bikramkawan** [comment]
Use case: 
Consider following attributes
![image](https://cloud.githubusercontent.com/assets/12292333/23831383/3d76ab40-0720-11e7-9516-45d7d3900779.png)

Step 1: Sorted by Career Status
![image](https://cloud.githubusercontent.com/assets/12292333/23831388/53d37512-0720-11e7-99b5-8cb7639ab5fb.png)

The gray  color will be the single multiform for column career status

Step 2: Sorted by Origin
![image](https://cloud.githubusercontent.com/assets/12292333/23831393/7887ade2-0720-11e7-8c64-2374051258a9.png)

The two different yellow will be two multiforms for column Origin 

Step 3: Sorted by Studio Albums
![image](https://cloud.githubusercontent.com/assets/12292333/23831410/b682bcb8-0720-11e7-9760-c6573af9c1f2.png)

Since we reach the numerical data, there will be only two multiform.

Step 4: Sorted by gender 
Since there, is already numerical column so the multiform will stay same for rest of the columns
![image](https://cloud.githubusercontent.com/assets/12292333/23831422/2414a21e-0721-11e7-9556-50e8fb1f82fc.png)

**Comment by bikramkawan** [comment]
Current State:
Col1: 1 Multiform 
Col2: 2 Multiforms 
Cols > 2  are using 6 Multiforms

The sorting is same as previous . 

![mar-12-2017 10-22-53 pm](https://cloud.githubusercontent.com/assets/12292333/23836077/85d1dfa2-0772-11e7-8990-0facb2432d60.gif)

Col 1 : 1 Multiform 
Col2 : 2 Multiforms 
Col 3: 6 Multiforms
Cols > 4 : 13 Multiforms
![mar-12-2017 10-27-44 pm](https://cloud.githubusercontent.com/assets/12292333/23836104/313b2eac-0773-11e7-899e-9ace115a78a9.gif)

**Comment by mstreit** [comment]
@bikramkawan, are you already able to switch the matrix to a stratified boxplot renderer?

**Comment by bikramkawan** [comment]
No. currently matrix is not switched to other representation rather than heatmap. I think it should be integrated with #212.

**Comment by mstreit** [comment]
No, it is not related to #212, but rather #56
