### ISSUE TITLE
Cells not highlighted consistently in all columns

### ISSUE THREAD

**Issue by alexsb** [Caleydo/mothertable#216]
![image](https://cloud.githubusercontent.com/assets/2039375/23838510/5bd82032-075c-11e7-8b44-eb7e9d7a102c.png)

The origin cells aren't highlighted.

**Comment by mstreit** [comment]
who can fix this?

**Comment by mstreit** [comment]
what is the problem here?

**Comment by bikramkawan** [comment]
I will have a look

**Comment by mstreit** [comment]
Fixed. 

![image](https://cloud.githubusercontent.com/assets/4129755/24013212/f2f43e66-0a80-11e7-8209-324c52ab5b48.png)
