### ISSUE TITLE
Improve data addition interface

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#219]
At the moment we have a very simple dropdown. 
It would be nice to show: 
- Name of the attribute
- Type of the attribute
- Dimensions (number of rows/columns)

Sketch from Mirka (a little outdated already)
![image](https://cloud.githubusercontent.com/assets/4129755/23848481/c8f9d428-07d7-11e7-8621-47c3cb4fe9e7.png)

**Comment by mstreit** [comment]
related to #63

**Comment by mstreit** [comment]
@alexsb, can you please add a sketch of the design that you had in mind? I remember that in one of our discussions we thought that it's a good idea to add all attributes to the side panel from the very beginning. We could then have a separation line that indicates which attributes are currently present in the table.

**Comment by mstreit** [comment]
![image](https://cloud.githubusercontent.com/assets/4129755/24052776/fe65724a-0b36-11e7-8ae5-4ce24d17b6da.png)

**Comment by alexsb** [comment]
Yes, that's roughly what I was thinking about. 

Drag and drop is nice, but sometimes impractical if you have to drag far. So I'd add +/- buttons.

**Comment by mijar** [comment]
how would you cover the situation, when the user would like to add e.g. Number1Hits twice to the Table view with different stratifiers in the vertical direction?

**Comment by mstreit** [comment]
good point. any suggestion?

**Comment by mijar** [comment]
First thought was keeping the matrices always available under the line, like a "neverending stack"...I am not sure if it will make sense to add the other attributes multiple times too...
Other thought was a "duplicate / clone" button in the Attribute panel, next to the move, remove and sort buttons
I am just making a refined sketch so we can see it clearer...

**Comment by mijar** [comment]
![ui_refined-01](https://cloud.githubusercontent.com/assets/7511570/24085025/cc944718-0cf4-11e7-9c28-e29ddf78ab54.png)

What I don't like that much in this approach of having all attributes in place is that event though you might have multiple matrices in the Table view, you would not see them in this case shown above....
I have included the second thought with the clone button concerning my last comment in the sketch

**Comment by mstreit** [comment]
Yes, but with the clone I would still not see to which of the multiple matrices the stratifying attributes belong to, right?
How about visually bundling the matrix with the attributes that could be used to horizontally stratify the matrix? This way each matrix would have its own set of stratifier attributes (depending on the ID of the column...). In the your example, the country attributes would be presented inside the number one hits matrix widget (collapsable).

**Comment by mstreit** [comment]
Very nice sketch btw 👍 
I would love to see it already implemented :)

**Comment by mijar** [comment]
nice idea Marc! I will change it in the sketch...

**Comment by mijar** [comment]
I put the sketches showing the behavior you proposed into the [gSlides presentation with the Mockup](https://docs.google.com/presentation/d/1I7y-VKfG02UyAIlYT_ZsklegRdiLz4rrrX5WiqO-hP0/edit#slide=id.g212ea52e2e_0_28):
slides 71-72 are showing just two variations of how to visually divide the panels
slides 72-74 are showing the collapsing behavior and preview of how much space we can most probably save by allowing this...

I am curious what you think :-)

**Comment by mijar** [comment]
In general, I think that showing the other attributes not currently shown in the Table view do not make that much sense without some preview of the data...I mean yes, it is useful to see what attributes you can add...but if the added value is worth the space it takes...

**Comment by mijar** [comment]
I left the concept from yesterdy in the presentation for a reference, but an updated interface is in [the same presentation](https://docs.google.com/presentation/d/1I7y-VKfG02UyAIlYT_ZsklegRdiLz4rrrX5WiqO-hP0/edit?usp=sharing) from slide 75 up

**Comment by mstreit** [comment]
I agree that showing the stratifiers for matrices on demand makes sense. But I still think that the attributes for the primary ID type should be present at the bottom. I don't like the indirection via the + button so much (for the primary ID type).

**Comment by mijar** [comment]
@thinkh mentioned at the standup quite nice counterexample when the approach with attributes at the bottom broke down and was not intuitive...because it became messy with the surrounding attributes. Holger do you remember the case in more detail?

**Comment by thinkh** [comment]
My point is, if user has the possible attribute of Artists and Countries (from a matrix) open at the bottom, it might be confusing which one will be added to which part. And the other point was that scrolling putting the attributes at the bottom requires a lot of scrolling and dragging up/down. Especially scroling while dragging is always tedious.

**Comment by mstreit** [comment]
maybe this was because of the list of possible stratifying attributes for each matrix that would move done the attributes of the primary ID types.  I don't think that we will have this problem when we show the matrix stratifiers on demand.

**Comment by thinkh** [comment]
Done for now with select2 implementation. -> Close
