### ISSUE TITLE
Find another dataset for guiding use case example

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#220]
We need to find another dataset for the simple use case that we use as a guiding example in the paper. With 12 element the artists dataset is way too small.

Any suggestions?

**Comment by mstreit** [comment]
We could use OECD data with some time aspect or alternatively this vaccine dataset with US states:
http://www.randalolson.com/2016/03/04/revisiting-the-vaccine-visualizations/

**Comment by mstreit** [comment]
Alex and I decided to use the AIDS dataset from http://aidsinfo.unaids.org/, which we will also take as a guiding example to introduce the concept.

With the different time steps for many of the attributes we also have lots of matrices. For the countries it's also easy to find additional meta-data such as population, size, GDP, etc.
The AIDS dataset itself also contains categorical attributes, such as 'law'.
In the other direction for the timesteps we can add additional categorical meta-data such as self-defined ones like "1980 - 2000 - no medication available" or others that we find in public sources (e.g., http://www.nature.com/nrd/journal/v6/n12/fig_tab/nrd2448_F1.html)

@mijar, can you please try to prepare this dataset as excel/CSV file until tomorrow noon? I know that this is very soon already, but we need this asap for explaining the concept. Once you have it in CSV format, @alexsb will create the JSON file that we can then use to load the data into Taggle.

**Comment by mijar** [comment]
@mstreit I will collect the data just for the whole population (all age categories), ok?
@alexsb what is the best way for you to store the matrices, with the rest of the attributes in one table or separately and named after the values they store?

**Comment by mstreit** [comment]
yes, all age is fine.

**Comment by mstreit** [comment]
oh, and please put everything in our taggle gdrive folder.

**Comment by mstreit** [comment]
Just as reference - generator script for Phovea Tables:
https://github.com/Caleydo/phovea_json_generator/blob/master/CreatePhoveaJson.ipynb

**Comment by alexsb** [comment]
Tables only though - adding matrix capabilities shouldn't be hard, but matrices are also easy to do by hand.

**Comment by mijar** [comment]
![image](https://cloud.githubusercontent.com/assets/7511570/24379207/4faa4eac-1346-11e7-9708-9dfdfd6a20bf.png)
...I have found a few things, will create issues for them
