### ISSUE TITLE
Increase minimum height of single rows in case space is available

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#222]
The height of the rows is so small that it's hardly possible to see labels. Let's use the same minimum height as for the string column rows. 

![image](https://cloud.githubusercontent.com/assets/4129755/23869829/be08e584-0824-11e7-94c0-2d915086c78e.png)

**Comment by mstreit** [comment]
@bikramkawan, this should be an easy fix, right?

**Comment by bikramkawan** [comment]
@katush and we discussed yesterday related to this. She should have probably done this I think. @katush Any update ?

**Comment by mstreit** [comment]
This seems to be addressed in the https://github.com/Caleydo/mothertable/tree/user_selected_visses_%23238 branch.

![image](https://cloud.githubusercontent.com/assets/4129755/24072115/e09e948e-0be1-11e7-8e91-40f59fe3c383.png)

**Comment by mstreit** [comment]
@katush, can you extract the change that fixes this issue from the https://github.com/Caleydo/mothertable/tree/user_selected_visses_%23238 branch and file a PR that just fixes the row height issue?

**Comment by thinkh** [comment]
@mstreit Could you please check again, if this is fixed. I'm not sure.

**Comment by katush** [comment]
should be, though the name of this issue is not precise - at least I think that the goal was to increase maximum height of rows - so they can still shrink, but if they have space, they will expand. That is what I have done

**Comment by mstreit** [comment]
Yes, it was about the max height.
