### ISSUE TITLE
Combining multiple single-value columns into one multivalue column

### ISSUE THREAD

**Issue by mijar** [Caleydo/mothertable#223]
Let's say we have 10 columns containing GDP for last 10 year, one column for 2006, one for 2007 and so on...I thought it might be beneficial to give the user a possibility to combine those columns into one that might make a use of Bikram's multivalue cell renderers. 
What do you think?

**Comment by mstreit** [comment]
Yes, that would be useful. But AFAIK the multivalue cell renderers are LineUp specific.
