### ISSUE TITLE
Mosaic plot not shown initially, only after resize

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#224]
### Steps to reproduce

1. Add categorical column
2. Switch visualziation to mosaic plot

### Observed behavior
* The mosaic plot has the initial of height=0
* After rescaling the height is set correctly

![taggle_no-mosaic](https://cloud.githubusercontent.com/assets/5851088/23912698/ce8e3d2a-08e0-11e7-8de9-1ed15e5b51c4.gif)

![taggle_no-mosaic-height](https://cloud.githubusercontent.com/assets/5851088/23912725/eaef2876-08e0-11e7-8846-c9654a13110c.png)

### Expected behavior
* The mosiac plot should be shown initially

**Comment by thinkh** [comment]
@Caleydo/project_mother-table Could you please have a look if you have this behavior, too?

**Comment by thinkh** [comment]
I re-installed the mothertable_product. I can't reproduce this error anymore. Seemed to be a local problem.

**Comment by katush** [comment]
@thinkh is the magic-box branch working than? that's where you first came across it.

**Comment by thinkh** [comment]
No, it was in @bikramkawan old branch `feature_#157`
