### ISSUE TITLE
Rows are out of sync

### ISSUE THREAD

**Issue by alexsb** [Caleydo/mothertable#225]
See this:

![image](https://cloud.githubusercontent.com/assets/2039375/23913242/f3b552fc-08a7-11e7-9bae-a147a7eda8a5.png)

Career Status in text label.

**Comment by mstreit** [comment]
probably related to scaling problems #207, #224

**Comment by bikramkawan** [comment]
Yes, It seems to be scaling function of multiform which is not updated for the list. @katush Is it?

**Comment by mstreit** [comment]
Works now.

![image](https://cloud.githubusercontent.com/assets/4129755/24013064/7a73e6bc-0a80-11e7-9c12-6def807dea36.png)
