### ISSUE TITLE
Add axis for numerical columns to headers 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/mothertable#227]
Add to the header here on the left: 

![image](https://cloud.githubusercontent.com/assets/2039375/23913615/2b157082-08a9-11e7-880b-49a5482336db.png)

**Comment by mstreit** [comment]
How about adding histograms that show the distribution and also the min/max + current brush?

**Comment by mstreit** [comment]
This is a must have for the final screenshots.

**Comment by thinkh** [comment]
Should we really add the axis to the column header? If all headers should have a uniform height, we have an empty space in other column headers, right?

**Comment by mstreit** [comment]
Datacomb shows the value of the current hover element in categorical columns.

**Comment by mstreit** [comment]
@alexsb?

**Comment by thinkh** [comment]
@katush It would look like in [datacomb](http://www.bytemuse.com/datacomb/demo/).

![grafik](https://cloud.githubusercontent.com/assets/5851088/24356330/cefcade6-12f9-11e7-8c93-88e46e7493b3.png)

**Comment by alexsb** [comment]
There should be a histogram in every column, so why would there be an empty header?

**Comment by alexsb** [comment]
And even if you don't want to do a histogram, we need the color labels for the categorical columns in the header IMO - the side panel is too far removed

**Comment by mstreit** [comment]
yes, adding a histogram is an alternative. but we already have the histograms in the filter. so we would have it twice then.

**Comment by thinkh** [comment]
But a histogram itself doesn't explain the length of the bar, because of the binning. So IMO we need the axis anyway.

**Comment by mstreit** [comment]
you can show min/max values for the histogram as well.

**Comment by mstreit** [comment]
We agreed to just add axis at the top

**Comment by mstreit** [comment]
![image](https://cloud.githubusercontent.com/assets/4129755/24419753/8cf11a34-13f0-11e7-8f91-6a522aa989ec.png)
