### ISSUE TITLE
Create blurred visualization

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#237]
The blurred vis is needed when the string vis multiforms switch to a higher level.

**Comment by mstreit** [comment]
Do we need this with our latest concept?

**Comment by bikramkawan** [comment]
At the moment its not necessary. We said we would use the brush for unaggregated vis.

**Comment by mstreit** [comment]
Yes, so the strategy is to not show the label if the row height is too small. However, the slim rows (that are empty) should still be brushable.

**Comment by mstreit** [comment]
Will be handled as part of the vis labeling issue (#173)
