### ISSUE TITLE
Add delete button to filter

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#240]
Add a delete button to the attribute filter (next to the sort direction button). On click all columns of this attribute should be deleted.

![grafik](https://cloud.githubusercontent.com/assets/5851088/24051019/01a8df6a-0b31-11e7-96e5-77f9b625493d.png)

**Comment by mstreit** [comment]
We need to discuss if we actually want to have it. Because it has consequences for the interface how to add columns and matrices (see #219).

**Comment by bikramkawan** [comment]
![2017-03-25_22-30-38](https://cloud.githubusercontent.com/assets/12292333/24326258/e671f292-11aa-11e7-8c73-4a2f06f661ed.gif)
