### ISSUE TITLE
Create horizontal multiform visualizations in phovea_vis

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#242]
At the moment the phovea_vis doesn't work in horizontal direction. We need to extend these visualizations so that we can use them in the column stratifications.

![taggle_column-stratifications](https://cloud.githubusercontent.com/assets/5851088/24060854/5eccc49e-0b55-11e7-9f56-2b41688cf668.gif)

**Note:** I deactivated the multiforms at in #241. Activate the column stratifications when implementing  (https://github.com/Caleydo/mothertable/commit/f367f057fc185c2797c82c77b55f7bb0a3dd07cf and https://github.com/Caleydo/mothertable/commit/4d66495d7228a0713c6a00029e2b0689de7ba7b5).

**Comment by mstreit** [comment]
@bikramkawan, for which visualizations did you implement the orientation switch now? heatmap and bar chart?
