### ISSUE TITLE
Stratify matrices by all categorical columns that are above the table in the sorting hierarchy

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#243]
![image](https://cloud.githubusercontent.com/assets/4129755/24071597/810d8e18-0bd6-11e7-82b5-08d133cac8ad.png)

**Comment by mstreit** [comment]
The splitting works once I add a numerical column. But as mentioned above, the matrix should also be split without a numerical column.

![image](https://cloud.githubusercontent.com/assets/4129755/24071711/e002c076-0bd8-11e7-849b-2fc06ce72df9.png)

**Comment by bikramkawan** [comment]
Yes, it was not the bug. It is intentional. The matrix was not part of the sort. The split of the matrix is same as preceding in the filter view.
I will look on this.

**Comment by mstreit** [comment]
Wont' implement.
