### ISSUE TITLE
Add interface for aggregating groups across all columns

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#246]
Add a small fixed size column that allows the user to switch for each stratified group whether it should be shown aggregated or non aggregated.

**Comment by mstreit** [comment]
Aggregated groups are always shown with a constant height (e.g., 20-30px).

**Comment by mijar** [comment]
![ui_refined_correct-01](https://cloud.githubusercontent.com/assets/7511570/24085134/5c478112-0cf6-11e7-88c3-6fdc589dbed7.png)

So origin is here a stratifier...and the aggregation column is the first one - full rectangle means it's aggregated, empty that we are on item level
