### ISSUE TITLE
Create Density Plot for numerical and Categorical in Filter Dialog

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#25]

**Comment by bikramkawan** [comment]
Current Status:
![jan-31-2017 3-23-52 pm](https://cloud.githubusercontent.com/assets/12292333/22468638/58f7a70a-e7c9-11e6-8155-7e7d8627ea75.gif)

**Comment by mstreit** [comment]
Let's discuss the filter histograms in our meeting today.

**Comment by bikramkawan** [comment]
Current State:
![image](https://cloud.githubusercontent.com/assets/12292333/22498994/4d232c9a-e85c-11e6-8769-66b28890f9a1.png)

**Comment by bikramkawan** [comment]
![feb-02-2017 9-08-44 am](https://cloud.githubusercontent.com/assets/12292333/22541555/5822b158-e927-11e6-862b-7f4cf141ddb8.gif)
