### ISSUE TITLE
Use same color mapping for rendered heatmap and heatmap image

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#250]
![image](https://cloud.githubusercontent.com/assets/4129755/24083244/e9dbef0e-0cd3-11e7-852b-00d2d1aae867.png)

The red heatmap is rendered on the client (because of its tiny size) while the bigger one is rendered on the server and shipped to the client as an image. That's fine but they should obviously have the same color mapping.

**Comment by mstreit** [comment]
@sgratzl, can you please take a look at this? will probably not take you very long...
it should be constant. greyscale is fine as well for now.

**Comment by sgratzl** [comment]
https://github.com/Caleydo/mothertable/blob/master/src/column/MatrixColumn.ts#L55

explicitly sets the color scale to the redish one. However, the redish one is not supported by the server right now. See also https://github.com/phovea/phovea_server/issues/16

**Comment by mstreit** [comment]
ok, then let's switch the color map back to greyscale (which will also be used in the filter view then).

**Comment by mstreit** [comment]
@bikramkawan, can you please take care of this?

**Comment by thinkh** [comment]
Fixed by switching to grey scale (svg) heatmaps.
