### ISSUE TITLE
Load data for TCGA use case

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#26]
Loading TCGA data for one of the tumor types is important because it gives a bigger dataset to play with during development. Furthermore, this will also be the dataset that our collaborators will use to provide feedback.

**Comment by mstreit** [comment]
@sgratzl, what is the easiest way to achieve this? Add the hdf data connector and put a TCGA hd5 package in the data folder?

**Comment by sgratzl** [comment]
exactly

**Comment by mstreit** [comment]
ok, great. can you please add this to the product so that the larger TCGA dataset appears in the daily build version?

**Comment by mstreit** [comment]
Please also let the rest of the mothertable team know where to the TCGA hd5 data file can be found.

**Comment by sgratzl** [comment]
```
cd mothertable_workspace
mkdir _data
cd _data
wget https://s3.eu-central-1.amazonaws.com/phovea-data-packages/TCGA_GBM_2014_04_16.h5
cd ..
git clone https://github.com/phovea/phovea_data_hdf.git
yo phovea:update
docker-compose build api
docker-compose up -d
```

**Comment by mstreit** [comment]
Great, thanks!

**Comment by mstreit** [comment]
@mijar, @katush, @bikramkawan, please add the data in your local dev environment, too.

**Comment by mijar** [comment]
I am getting a wget: command not found and was not yet able to find how to install it...I am going to the defense now and will continue looking for it afterwards, if you would not be faster and help me.:-) thanks

**Comment by mstreit** [comment]
wget is just a command to download a file. you can also download the file via your browser and put it in the _data folder.

**Comment by bikramkawan** [comment]
If you are getting wget command not found you can simply download and place the file in _data folder. It worked for me.

**Comment by mijar** [comment]
Oh I see. Thank you.
