### ISSUE TITLE
Remove gradient from histogram

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#260]
![image](https://cloud.githubusercontent.com/assets/4129755/24244386/e4660706-0fbe-11e7-9a2d-6c8cc82da662.png)

I don't know what the purpose of the gradient in the histogram is. But for Taggle it can definitely be removed (maybe turn it off using a flag, if we need the functionality somewhere else).

**Comment by sgratzl** [comment]
see https://github.com/phovea/phovea_vis/pull/44

**Comment by mstreit** [comment]
Done. 
![image](https://cloud.githubusercontent.com/assets/4129755/24322509/d3867f30-1165-11e7-9bd3-772ec1eee3dd.png)
