### ISSUE TITLE
Non-determinisstic matrix scaling

### ISSUE THREAD

**Issue by katush** [Caleydo/mothertable#264]
Upon adding the matrix to the table, the matrix is often (not always) scaled incorrectly and also breaks the size of the whole table (except for the agg. switcher column)
![image](https://cloud.githubusercontent.com/assets/8986080/24257356/f2ab1db6-0fea-11e7-941c-643058455eba.png)
After next re-layout call, the scaling is again correct.
Seems that when the matrix is added and the re-layout is called, the data are not there yet.

**Comment by bikramkawan** [comment]
Steps to reproduce:
1: Add career Status
2.Add Number on hits
I am also facing this when adding stratification from other direction of the matrix. It is throwing error on
![image](https://cloud.githubusercontent.com/assets/12292333/24322248/bedbd6bc-115f-11e7-9149-7a0f6934c87a.png)

**Comment by mstreit** [comment]
@bikramkawan, please don't mix issues. Your comment is related to #43 and should be posted there.

**Comment by mstreit** [comment]
I'm tempted to add a new label "super important"
