### ISSUE TITLE
Fix visualizations

### ISSUE THREAD

**Issue by katush** [Caleydo/mothertable#265]
- [x] Fix the order of histogram (flag)
- [x] Fix the color of boxplot - should be grey (see #260)
- [x] Remove gradient from histogram (use grey)
- [x] Add space between heatmap = border
- [x] Remove the border around rowbase visses if the rows are small

**Comment by bikramkawan** [comment]
Histogram Color:
![image](https://cloud.githubusercontent.com/assets/12292333/24322494/9f2a3b1e-1165-11e7-8e5f-4f626cea7741.png)

**Comment by bikramkawan** [comment]
Boxplot:
![image](https://cloud.githubusercontent.com/assets/12292333/24322506/baf41770-1165-11e7-8624-a2afaff36053.png)

**Comment by mstreit** [comment]
Not everything on the list is fixed yet. Reopening issue.

**Comment by bikramkawan** [comment]
Sorting histogram
![mar-25-2017 4-07-40 pm](https://cloud.githubusercontent.com/assets/12292333/24323414/384f1120-1175-11e7-8265-deec7a3435e8.gif)

**Comment by thinkh** [comment]
> Add space between heatmap = border
Done with https://github.com/Caleydo/mothertable/commit/075f165778386aaa72971a5a3866fdcc6626b59f

![grafik](https://cloud.githubusercontent.com/assets/5851088/24325189/d407ac26-1193-11e7-8980-d8d9cfe9726b.png)

**Comment by thinkh** [comment]
> Remove the border around rowbase visses if the rows are small
For the remaining todo I opened a new issue https://github.com/Caleydo/mothertable/issues/271.

-> I close this issue.
