### ISSUE TITLE
Use select2 for attribute selection

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#266]
For the TCGA use case we will have thousands of different attributes (e.g., mutation for gene X). So the select2 box is the perfect solution to address this problem. 
Also add an icon for each entry encoding the attribute type.

Related to #219.

**Comment by thinkh** [comment]
![taggle_select2](https://cloud.githubusercontent.com/assets/5851088/24333108/efe9e3ae-1252-11e7-8245-2617fc6a3454.gif)

**Comment by mstreit** [comment]
Nice!
