### ISSUE TITLE
Create initial version of column manager

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#27]
The column manager should assign new columns for each dataset a user selects. The manager should also take care of assigning space to the columns. The columns itself (own class) should then decide on its own how to fill this space and how the data needs to be aggregated given the assigned space.

@sgratzl will create an initial version where @katush and @mijar can then continue with working on the different features.

**Comment by sgratzl** [comment]
I created an initial version at https://github.com/Caleydo/mothertable/tree/feature_columnManager/src/column

However, I don't know how to integrate it in the current setup, since I don't fully understand how different components are working together.

**Comment by mstreit** [comment]
@mijar, do you know how the different components work together?

**Comment by katush** [comment]
right now the class VisManager partially covers functionality/responsibility  of Sam's the ColumnManager so I think the pest place to start is to try and merge these two

**Comment by mstreit** [comment]
OK, I've discussed this with Sam. He will implement an overall architecture so that you have a clean state to continue. Updates will be posted in this ticket soon.

**Comment by sgratzl** [comment]
done: 
 * initial idtype selection 
 * area for filter manager
 * adding/removing of columns
 * column manager 
todo: 
 * a matrix columns is also a column manager

**Comment by mstreit** [comment]
Cool. I think the easiest way is to make this branch the new master and integrate the now missing functionality in the redesigned class structure.

**Comment by sgratzl** [comment]
why? the old elements are still around. I created the app in parallel to the other one

**Comment by mstreit** [comment]
I know, but now the question is how the rest of the team should continue.

**Comment by sgratzl** [comment]
why not just merging this branch into the master branch as always?

**Comment by mstreit** [comment]
I thought that the implementations in the two branches are complementary. But if that's not the case then let's merge them.
