### ISSUE TITLE
Restyling of filter histograms

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#273]
As we don't use the red color map anymore in the table view, we should also switch back to a greyscale histogram. To still be able to differentiate between the included part and the filtered part, I suggest to apply a hatching pattern to the filtered area.

![image](https://cloud.githubusercontent.com/assets/4129755/24325517/c039ced4-119a-11e7-8883-167fac74f546.png)

**Comment by thinkh** [comment]
Hatch pattern: https://iros.github.io/patternfills/sample_d3.html

**Comment by mstreit** [comment]
coloring is also part of #250

**Comment by bikramkawan** [comment]
Better ?
![image](https://cloud.githubusercontent.com/assets/12292333/24353322/514e8b1e-12ed-11e7-8813-ccd958cbc5f7.png)

**Comment by mstreit** [comment]
yes!
