### ISSUE TITLE
Pop-up toolbar for small groups

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#276]
For small groups the height is too small to accommodate the three switcher icons. To address this issue we could create a pop-up toolbar showing up when the user hovers over the first switcher column.

Coming from #246.
![image](https://cloud.githubusercontent.com/assets/4129755/24330050/9eccf10a-1216-11e7-86b5-4ede9d30f6ef.png)

**Comment by katush** [comment]
A slightly different issue, but since this was referenced from issue #348 I think  it is also relevant to have popup toolbar at the top of the column instead stretching in following way:
![image](https://cloud.githubusercontent.com/assets/8986080/25942746/e86b1058-363d-11e7-8d6b-781e9d837140.png)

**Comment by thinkh** [comment]
Done by @katush.

![grafik](https://cloud.githubusercontent.com/assets/5851088/26592027/d2905064-455f-11e7-8b83-e68730e8c39a.png)

**Comment by katush** [comment]
@thinkh I think this issue was originally ment as pop-up for aggregation switcher column icons (column not toolbars), it just somehow got mixed up...

**Comment by sgratzl** [comment]
https://github.com/Caleydo/taggle/commit/06bb22d8e53cbce4dcb7d9a5f33bcf53bce4b6d5 hides them for now if there is not enough space

**Comment by NMO13** [comment]
![image](https://user-images.githubusercontent.com/3988444/27482952-b1748cb6-5823-11e7-9340-5509c93e098e.png)
From a functionality point of view, it is fine because you can still click on "aggregation".  It is more a visual problem, because the cropped icon look a bit ugly.
