### ISSUE TITLE
Wrong multiform splitting after brush

### ISSUE THREAD

**Issue by katush** [Caleydo/mothertable#278]
When there are brushed elements and the user adds new column or changes stratification, the new multiforms are not split correctly - the "brushed" multiforms also contain items that weren't brushed.

**Comment by mstreit** [comment]
Same happens if one brushes too fast so that some of the elements are not included in the brush but still get bigger.

![image](https://cloud.githubusercontent.com/assets/4129755/24330165/057ed164-1219-11e7-81bb-9c229b642308.png)

**Comment by mstreit** [comment]
@katush, is this issue solved?
I will extract the problem from my comment to a separate issue.
