### ISSUE TITLE
Make FilterManager for different IDTypes

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#28]
The first user will choose the different IDTypes (like Artist or Countries)
Then if there are two idtypes there will be two filter manager for each idtypes.
There will be dropdown selection for each idtypes which will contain all the data it holds
For example in Artist: the data could be artist name, gender, origin
In idtype of countries, the data could be continent, sold albums 

![img_0245](https://cloud.githubusercontent.com/assets/12292333/22477691/4dd50840-e7e7-11e6-89f7-0867779b3d83.JPG)

**Comment by mstreit** [comment]
Yes, making the addition of data more structured is definitely a good idea. I also agree with Alex that we can integrate this in the view on the right.

**Comment by mijar** [comment]
Bikram just a check if I understand - so there will be only a dropdown with selection of IDType and the rest of the content will be changing according to your selection? 
How will you then deal with the case of 2 matrices in the Table?

**Comment by mstreit** [comment]
Yes, the first dropdown basically just determines the primary ID type for the table, i.e. rows. 
For each matrix you select, we can add a new filter view for the corresponding column type.

**Comment by mijar** [comment]
I understood it as the dropdowns are all the same one dropdown, that is just driving what is shown in filter view...

**Comment by mstreit** [comment]
The goal is to structure and subdivide the potentially long list of possible data subsets a user can add. If the user selects 'artist' as a primary ID type, the newly added ID type specific area will show a drop down with all subsets associated with artists - including matrices. In this ID type specific area will will also place the corresponding filters. If a user selects a matrix, it will be added to the main table and in addition, we also add another ID type specific area for the second ID type the matrix contains (e.g., country).

**Comment by mijar** [comment]
Now I understand how you meant it, thanks for the explanation. Nice and useful idea.
The only thing about this might be that in this setup, the additional view will always have to be there and not hideable...I am fine with that, just pointing it out because in general it has been agreed that this area should be shown only on demand

**Comment by mstreit** [comment]
We could still show it on demand or if the user moves the mouse to the right side. Or is there another reason that I missed why this is not an option anymore?

**Comment by mstreit** [comment]
Works in principle. Fine tunings and open issues will be filed as separate tickets.
