### ISSUE TITLE
Broken sorting for numerical columns as first column

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#292]
### Steps to reproduce

1. Add numerical column as first column
2. Sort columns from column or filter

### Observed behavior

![taggle_sort-first-column](https://cloud.githubusercontent.com/assets/5851088/24347108/83cf6cea-12d7-11e7-9fb2-fcf11abe02f9.gif)

### Expected behavior
* Sorting the first column should work

**Comment by mijar** [comment]
in this setup, it does not react to filtering values either

**Comment by bikramkawan** [comment]
Filter is also fixed.

**Comment by bikramkawan** [comment]
![mar-28-2017 10-28-07 pm](https://cloud.githubusercontent.com/assets/12292333/24425860/ee6d7cd4-1405-11e7-9937-4808562ef674.gif)
