### ISSUE TITLE
Set y-scale of histograms on a per-column basis

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#299]
Our bars in the histogram get smaller and smaller the more bins we have. We need to find out what the highest bin is in all histograms contained in a Taggle Column and set this as a max in all histograms.

**Comment by mstreit** [comment]
Let's calculate the histogram for all elements in the column and use the value of the largest bin as a max in the y-scale for all histograms across the groups.

**Comment by thinkh** [comment]
Done.

![grafik](https://cloud.githubusercontent.com/assets/5851088/24370258/1314480e-1327-11e7-88af-5228bb348ca8.png)

**Comment by mstreit** [comment]
Now the histograms are finally meaningful!
