### ISSUE TITLE
Add sorting in header of column

### ISSUE THREAD

**Issue by katush** [Caleydo/mothertable#3]
Introduce and synchronize sorting of items in blocks.

**Comment by bikramkawan** [comment]
Alphabetical and Numerical 
on commit 
Numerical: https://github.com/Caleydo/mothertable/commit/f77ebdf0070a6caec99e9f5afbc0dfa261af48a3
Alphabetical: https://github.com/Caleydo/mothertable/commit/aca5da6191893402a552ff8a6af8aba706bb2bc5

**Comment by mstreit** [comment]
Is this done? If not, what needs to be implemented before we can close this issue?

**Comment by bikramkawan** [comment]
Not Done yet completely

**Comment by mstreit** [comment]
what is missing?

**Comment by mstreit** [comment]
Matrix block has a different sorting numerical and categorical columns.

**Comment by bikramkawan** [comment]
Add toggle function in header for ascending and descending order

**Comment by mijar** [comment]
@bikramkawan the button is the only thing that is missing?

**Comment by mijar** [comment]
The button is there now, should appear after PR approval.
