### ISSUE TITLE
Unify number of bins for same column across all groups

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#301]
![image](https://cloud.githubusercontent.com/assets/4129755/24362462/26f212f8-130d-11e7-8aa8-eb26b368c4ab.png)

Related to #299

**Comment by mstreit** [comment]
Let's calculate the histogram for all elements in the column and use the same number of bins for stratified histogram

**Comment by mstreit** [comment]
It will also look much clearer then.

**Comment by thinkh** [comment]
Done.

![grafik](https://cloud.githubusercontent.com/assets/5851088/24370250/0c20590c-1327-11e7-878f-3eda57a20a74.png)
