### ISSUE TITLE
selection of a column in matrix results in selection of additional column in other matrix

### ISSUE THREAD

**Issue by mijar** [Caleydo/mothertable#319]
![image](https://cloud.githubusercontent.com/assets/7511570/24422854/3e2a077a-13fb-11e7-87d4-8f00f8eb2026.png)

I selected the last column in the normalized matrix and this happened...I don't think it's wanted?

**Comment by mstreit** [comment]
As we take years as column IDs, they match across matrices. I think it's fine because the user can then associate the same year between different matrices.

**Comment by mijar** [comment]
ok

**Comment by mstreit** [comment]
If only all issues would be that easy to fix :)
