### ISSUE TITLE
Add a possibility to hide a column

### ISSUE THREAD

**Issue by mijar** [Caleydo/mothertable#321]
Before the AIDS_Years addition:
![image](https://cloud.githubusercontent.com/assets/7511570/24423262/ac000186-13fc-11e7-864c-570e2d509b44.png)

After:
![image](https://cloud.githubusercontent.com/assets/7511570/24423228/97a62c24-13fc-11e7-80c6-6398d3b7896a.png)

The AIDS-related deaths are total number of deaths in all countries in the world and the number is decreasing with every year thanks to the treatment. Thus the interpretation is misleading now before we add the ID attribute that is just the year...

I know that the ordering is driven by the height of the bars, but in this case it's just not easy to follow...

**Comment by mijar** [comment]
maybe have the possibility to *hide* a column? to keep the ordering, but I don't want the ID to be there... I propose a toggle button with eye icon in the attribute panel

**Comment by mstreit** [comment]
yes, that would be a good solution.

**Comment by alexsb** [comment]
I think a better solution would be to treat temporal data differently and simply sort by year.
