### ISSUE TITLE
Stratification icon not showing up when dragging a categorical attr over a numerical one

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#323]
### Steps to reproduce

1. Add categorical
2. Add numerical
3. Add another categorical
4. Drag second categorical to be second in the hierarchy

### Observed behavior
* No stratification icon in filter view

### Expected behavior
* If the second categorical column is below the first categorical column in the sorting hierarchy, it should be ably to stratify it as well.

**Comment by bikramkawan** [comment]
I tried this in the master just now. Did you tried on master ?
![2017-03-28_21-58-26](https://cloud.githubusercontent.com/assets/12292333/24424737/01a51b3a-1402-11e7-9dc8-068a15b96f74.gif)

**Comment by mstreit** [comment]
Aha, yes. With the master it works.
