### ISSUE TITLE
Set colors for categorical attributes in artists dataset

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#34]
For now, only the colors for gender are set. All categorical attributes should get some color. Makes it also easier to see if filters work.

**Comment by mstreit** [comment]
@bikramkawan, you've addressed this issue already, right? Please don't forget to reference the issues in your commits and keep the status of the issues up-to-date.

**Comment by bikramkawan** [comment]
I did that Sorry I forgot to update here.
https://github.com/Caleydo/mothertable/commit/301234c0af981e4ec05fd6fadcbd89dbfa8c303f
