### ISSUE TITLE
Replace data  type icons

### ISSUE THREAD

**Issue by alexsb** [Caleydo/mothertable#349]
#I find the data type icons a little confusing, especially the numerical icon looks like the sorting icon. 

I'd instead go for something like this: 

![image](https://cloud.githubusercontent.com/assets/2039375/25363818/e34e43cc-291a-11e7-81d9-8fc9aa6e5c51.png)

Or this: 

![image](https://cloud.githubusercontent.com/assets/2039375/25363845/1be80d1c-291b-11e7-8733-a278dddbf902.png)

We need icons for: 

Labels / text - probably "T"
Numerical - probably "#"
Categorical - probably the three dots show above
Nominal (string) - probably the three numbers shown above

**Comment by alexsb** [comment]
The matrix icon is OK, but it could also be a variant of these icons, to reflect the nested datatype

**Comment by mstreit** [comment]
Take from http://fontawesome.io/icons/

**Comment by NMO13** [comment]
@alexsb  Where did you find the icons that you have posted above? I have looked at fontawesome but haven't found your icons so far.

**Comment by alexsb** [comment]
The first set is from Kitware's Resonant: https://resonantlab.kitware.com/

Probably custom made, but I'm sure it's open source. 

The second is tableau.

**Comment by thinkh** [comment]
Moved to https://github.com/Caleydo/taggle/issues/133
