### ISSUE TITLE
Numerical filter bugs

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#35]
- [x] it is currently hard (sometimes impossible) to include boundary values again after you previously filtered them out
- [x] it is impossible to select only small range in the middle of the range of values - the other handle of the slider starts moving because of the size of the handle
- [x] reimplement this with d3 brushing, it's nice and easy to interact with

**Comment by bikramkawan** [comment]
I think I can close this now right ?

**Comment by mstreit** [comment]
If the problem does not occur anymore, yes.

**Comment by mijar** [comment]
I added a more detailed description of the problems in the top comment @bikramkawan ...

**Comment by bikramkawan** [comment]
Thanks @mijar

**Comment by mijar** [comment]
the brushing is covered in #46 , just putting here a reference so then both issues can be deleted.

**Comment by bikramkawan** [comment]
![feb-27-2017 10-46-05 pm](https://cloud.githubusercontent.com/assets/12292333/23381420/a09f168a-fd3e-11e6-8bde-a224892ab865.gif)

**Comment by mstreit** [comment]
@bikramkawan, is this issue still valid? 
Don't forget to regularly go through the issues and keep them up-to-date. If only a part of an issue is open, create a new one and reference it.

**Comment by bikramkawan** [comment]
It is still waiting to be merged. Reference #141
