### ISSUE TITLE
Blocks in the column layout should always fill the vertical space

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#36]
As a start, I suggest to let the blocks within the columns always fill the vertical space they have. In the current implementation, they are sometimes shown in full height, and sometimes they are only 100px height.

**Comment by mstreit** [comment]
Example: Rows in the bar block should have the same size as rows in the heatmap block

![image](https://cloud.githubusercontent.com/assets/4129755/22648154/8d12990e-ec75-11e6-8e3f-14d17a831f16.png)

**Comment by mstreit** [comment]
@katush, is this also fixed as part of PR #147?

**Comment by mstreit** [comment]
related to #150

**Comment by mstreit** [comment]
@katush, this is fixed, right?

**Comment by katush** [comment]
Yes, it is fixed
