### ISSUE TITLE
Width of the columns should be set depending on the block it contains

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#37]
In the current implementation all columns have the same width. As a starting point, the width of the column should be set according to the block width. The goal is to get rid of the white space between the blocks in order to see an actual table.

**Comment by mstreit** [comment]
@mijar, this is already done, right?

**Comment by mijar** [comment]
there are dummy values set right now, for easier debugging...I would like to leave this open because it reminds me to then better set these values

**Comment by mstreit** [comment]
related to #170 (see @bikramkawan's list)

**Comment by mstreit** [comment]
duplicate of #170
