### ISSUE TITLE
CategoricalFilter crashes with null values

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/mothertable#372]
reproduce: 
 * load a dataset in which there is categorical value which is null

```
CategoricalFilter.ts:209 Uncaught (in promise) TypeError: Cannot read property 'toUpperCase' of null
    at CategoricalFilter.catObjectsort (http://localhost:8080/app.js:37809:22)
```

**Comment by thinkh** [comment]
@sgratzl Which dataset and attribute can I use to test it?

**Comment by sgratzl** [comment]
I used the tourguide ones. However, you could hack one of your local one and introduce a null value

**Comment by thinkh** [comment]
Mh, in my test I can't confirm that...

![grafik](https://cloud.githubusercontent.com/assets/5851088/26717387/8269f12e-477d-11e7-847e-eecc9a32a502.png)

**Comment by sgratzl** [comment]
is the value empty "" or null?

**Comment by thinkh** [comment]
I tried both. The first one with "" and here with `null`:

![grafik](https://cloud.githubusercontent.com/assets/5851088/26717603/4b4d9ae6-477e-11e7-9719-c73c8851a138.png)

**Comment by sgratzl** [comment]
in this case the value is "null" not `null` - I'm not sure whether you can hack the csv to create real null values. + if you just take a look at the exception it makes sense that is crashes.

**Comment by thinkh** [comment]
Yes, you're right. I will just wait for a fix. ;-)
