### ISSUE TITLE
Allow change of matrix aggregation function

### ISSUE THREAD

**Issue by katush** [Caleydo/mothertable#396]
In aggregated matrix (vector) it would be nice to have possibility to change the aggregation function without having to de-aggregate the matrix first (keep the aggregation combo box in the toolbar)

**Comment by bikramkawan** [comment]
![2017-06-19_17-20-56](https://user-images.githubusercontent.com/12292333/27292493-e7229348-5513-11e7-84fd-3167b2c9cd0f.gif)
