### ISSUE TITLE
Create FilterManagement class

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/mothertable#4]
acts as a container and manager for the invidiual filters

**Comment by mstreit** [comment]
@bikramkawan, did you already implement your filter functionality using such a management class? If yes, please close this ticket.

**Comment by bikramkawan** [comment]
Done here.
https://github.com/Caleydo/mothertable/commit/7c486b8c74e8d4fb37b10aebe1b2d95420ca14c2
