### ISSUE TITLE
Data not encoded in URL

### ISSUE THREAD

**Issue by katush** [Caleydo/mothertable#404]
I am not sure if this is realistic, but here are some things that are not yet encoded in URL:
- Values that are filtered out
- Actual order of columns in table view
- Duplicate columns
- Types of selected visualizations per column
- Selected aggregation types

**Comment by thinkh** [comment]
Yes, that's true. However, we aggred at the beginning that we want to have a simple mechanism to restore a state (as good as possible). If you want to encode all these additional parameter, the URL hash might exceed [2000 characters](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers#417184) easily. 

The better alternative would be to integrate the provenance (aka CLUE).

**Comment by katush** [comment]
Sure, as I said I am not claiming it is realistic to encode it :) Just that it would be nice to be able to store it somehow seeing as I spent half the time yesterday recreating same states, after one or other issue broke it.
