### ISSUE TITLE
Set correct minimum and maximum when matrix is converted into vector for rendering

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#414]
There is wrong scaling of minimum and maximum when matrix is converted into stratified vectors. 

Observed Behaviour:
![image](https://user-images.githubusercontent.com/12292333/27287367-a7c3c63c-5503-11e7-9527-411522a0d1bf.png)
The matrix is first stratified based on continent and converted into min aggregation function.
The first column in the matrix belong to Australia, second is Europe and third one is North America. 
As you can see the minimum value of the Australia is 3 , Europe is 0 and North America is 0. And the minimum value of whole matrix is 0. While rendering the bar is incorrect. It is taking minimum value  independent of each one.

Expected Behaviour:
The bar of whole three columns should be scaled based on the minimum value of whole matrix i.e. 0 and maximum value 23.

**Comment by sgratzl** [comment]
see https://github.com/Caleydo/taggle/blob/master/src/column/NumberColumn.ts#L107
