### ISSUE TITLE
Add additional attributes at the top of the matrix block

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#43]
Should work with numerical and categorical attributes.

![image](https://cloud.githubusercontent.com/assets/4129755/22648047/fa3e3e08-ec74-11e6-8ff3-5f9bbe20a97f.png)

**Comment by thinkh** [comment]
@mijar I'll take over that one.

**Comment by thinkh** [comment]
@bikramkawan is currently working on that.

**Comment by bikramkawan** [comment]
![2017-03-26_20-14-18](https://cloud.githubusercontent.com/assets/12292333/24333916/f6f4f18a-1260-11e7-8bf7-9c3c95fff44a.gif)

**Comment by mstreit** [comment]
very nice.

**Comment by mstreit** [comment]
The height of the horizontal 1D heatmap can be reduced.

**Comment by mstreit** [comment]
Can you move the labels to the left side so that we don't need spacing between the different meta-rows?

**Comment by mstreit** [comment]
And please also post a screenshot with TCGA data.

**Comment by bikramkawan** [comment]
Ok The height can be fixed easily

**Comment by bikramkawan** [comment]
@thinkh Thanks for css trick :)
![image](https://cloud.githubusercontent.com/assets/12292333/24334542/44ab1afc-126c-11e7-8b97-4aefb81a7ec5.png)

**Comment by mstreit** [comment]
The 1D heatmap should have the same height as the max row height.
The vertical bar chart can stay as it is.
Make the padding between the horizontal vis and the label a bit smaller so that the association is more obvious.

**Comment by mstreit** [comment]
What about adding the additional attributes at the bottom so that we don't have the problem with the header?

**Comment by bikramkawan** [comment]
@mstreit Do you mean something like this? If we have attributes on top and bottom at the same time.
![image](https://cloud.githubusercontent.com/assets/12292333/24334672/e88a3a84-126e-11e7-8d56-db302f1fe73f.png)

**Comment by mstreit** [comment]
yes, exactly. @alexsb and rest of the team, what do you think? 
@bikramkawan, please use the max row height of the main table also for the 1D horizontal heatmap

**Comment by mstreit** [comment]
in the future we could let the user decide whether to add it at the top or at the bottom - by using drag and drop.
