### ISSUE TITLE
Attribute block disappears from Filter View even though it is still present in Table View

### ISSUE THREAD

**Issue by mijar** [Caleydo/mothertable#45]
When you add an attribute twice, it appears only once in the fiter view, which is correct - the problem is when you want to delete one instance of this attribute in table view and keep the other - the corresponding block in the filter view disappears.
1. Add origin
2. Add Career status
3. Add origin again
4. Delete one of Origin columns from Table View

![1attrtwice](https://cloud.githubusercontent.com/assets/7511570/22686119/30b629ba-ed23-11e6-9787-5b3f11b61889.PNG)

**Comment by mstreit** [comment]
Seems to be fixed now, right? @bikramkawan, please close the issues once they are addressed!

**Comment by bikramkawan** [comment]
yes.
