### ISSUE TITLE
Handles in numerical filters

### ISSUE THREAD

**Issue by mijar** [Caleydo/mothertable#46]
I would suggest the following behaviour:

- the size of the handle does not limit the user in the selection of desired interval
- once moved somewhere in the block, the handles do not change their position by themselves, only by interaction
- moving some handle does not affect the position of the other
- **maybe use gray handles and change the color to black and status to draggable on hover to allow selection of even tiny intervals?**

I guess we should also allow to create discontinuous intervals, something like this:
![numerical filter-01](https://cloud.githubusercontent.com/assets/7511570/22686793/d252fc1a-ed25-11e6-9014-7b6d1b875f4b.png)

**Comment by mstreit** [comment]
I would expect that the brush works as shown in the block example here (without the zooming of course):
https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

**Comment by mijar** [comment]
handles need to be made smaller and there has to be bigger margin to the border of the window - because right now border values can be missed out because you are not able to move the handle to the very end of the range.

**Comment by bikramkawan** [comment]
I have added some more space for now. I will update the brushing function as mentioned above.

**Comment by mijar** [comment]
good, the brushing has lower priority as we discussed, so you can focus on other issues now

**Comment by bikramkawan** [comment]
See Here: #35
