### ISSUE TITLE
Add new section in Filter View if Matrix is added twice

### ISSUE THREAD

**Issue by mijar** [Caleydo/mothertable#50]
If matrix is added for the first time, the section is created...if we want show the same matrix for the second time (e.g. with different stratification) the corresponding section in Filter View is not yet created

**Comment by mstreit** [comment]
Seems to work. Please re-open if this is not the case.

![image](https://cloud.githubusercontent.com/assets/4129755/23497033/9a8ca8a4-ff21-11e6-9ddf-520492704760.png)
