### ISSUE TITLE
Filters after column deletion - keep them and if we add the column again, show correct block appearance in filter view

### ISSUE THREAD

**Issue by mijar** [Caleydo/mothertable#51]
What should happen, if we delete a column where we have filtered something out in the corresponding block in filter view?
e.g. columns of gender, career status ...we filter out inactive artists, then delete the career status column.

- A) the vis should come to the state before the career status filter was applied
- B) keep the filter - but currently we lose track of it, because the column with the header is deleted and the corresponding block thus as well...(and currently - if we add the career status again, the filter view has both categories as selected, not inactive grayed out)

**Comment by mstreit** [comment]
I think option B is favorable.

**Comment by mijar** [comment]
the management here is not working properly, try this scenario:

1. add gender, career status and label, to see the difference (12 entries)
2. filter out active artists, to see only inactive ones (5 entries)
3. delete career status column (still 5 entries)
4. filter out females (is 8 but should be 4, because the career status filter should be still active as agreed before)
5. add column of career status again - you can see that the active ones are in the selection again
