### ISSUE TITLE
Row brushing for item level

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#54]
Transition to item level: When the label column is added and the items on individual level fit the screen, the table will be expanded to item level. If it doesn’t fit the screen, the top ten items will be expanded and the rest of the table will stay aggregated. The number of expanded items can be adjusted by brushing on label column. To aid brushing we will support snapping to multiples of 5.

![image](https://cloud.githubusercontent.com/assets/12292333/22695255/74346388-ed4a-11e6-81cd-932790e77726.png)

**Comment by mstreit** [comment]
related to #157

**Comment by bikramkawan** [comment]
Case : 
Each box represents multiform:
When user performs dragging this will not trigger the sorting event. The sorting result should stay same. 
Before Dragging 
![image](https://cloud.githubusercontent.com/assets/12292333/23992572/ae36b378-0a3d-11e7-9939-014016a7b5b3.png)


Now user start dragging from U2 to The Black Eyed Peas 

![image](https://cloud.githubusercontent.com/assets/12292333/23992578/b586550c-0a3d-11e7-84d2-7cfd31d1421a.png)

**Comment by mstreit** [comment]
What am I supposed to see here? Why is the brushed area split up in three multiforms?

**Comment by mstreit** [comment]
btw: it's called brusing and not dragging

**Comment by mstreit** [comment]
Now I get it after your explanation. The arrow marks 4 rows that are selected. That's why the multiform is split up in three.

**Comment by bikramkawan** [comment]
*updated figure. I think it should be now clear.

**Comment by bikramkawan** [comment]
Current state:
I have added brushing event listener for single multiform only. If the user is brushing from one multiform to another multiform, it will not work. We have thought to alternatives which can be discussed in meetings:

To Do: Add an extra flag in multiform for the brushing area to give more space.

The point of discussion:
- Add separate column only focus for brushing. This will make listening to the brushing event easy. 
![image](https://cloud.githubusercontent.com/assets/12292333/24048101/26b7e3e0-0b28-11e7-9eb3-6ad8610f47db.png)

**Comment by mstreit** [comment]
Some things we need to agree upon soon: 
- Should the brushing be done in a dedicated brush column that is added by default or should the user be able to set a brush in every column? Technically the second one is much more difficult of course.
- Should the brushing be independent of selections or should it be the same thing?

@alexsb @mijar and others: your input is welcome!

**Comment by alexsb** [comment]
Brushing == selections. 
I'd advocate for brushing at every element. 
How is cross multiform brushing a problem? For dragging events?

**Comment by mstreit** [comment]
In general I agree that brushing == selections and that we just need to give selected items more space. It gets problematic though because the user would never be able to see the immediate context (neighboring rows) for single item selections. That's why we could discuss to let the user increase the zoom level for certain parts of the table -- independently of the selected items.

Re cross multiform brushing: Yes, it's difficult in terms of event handling.

**Comment by bikramkawan** [comment]
At the moment the mouseup and mousedown can only listen to the current multiform. The mouse event loses the context when moving to another multiform.

**Comment by mijar** [comment]
The in-place manipulation is always better for the user (all elements can listen to the brushing) but on the other hand, in the sketches we considered brushing only in "id" column (names for artists) and it worked fine in my mind...

**Comment by bikramkawan** [comment]
![mar-18-2017 3-10-29 pm](https://cloud.githubusercontent.com/assets/12292333/24072818/1c2b3196-0bed-11e7-8cf4-b63afc8e4c14.gif)

**Comment by mstreit** [comment]
Looks good. But what happens if some of the multiforms are switched to a histogram/boxplot for instance?

**Comment by bikramkawan** [comment]
When switching vis, 
![mar-18-2017 3-20-37 pm](https://cloud.githubusercontent.com/assets/12292333/24072911/959372fe-0bee-11e7-96c1-b2dad9590add.gif)

**Comment by bikramkawan** [comment]
There is some overlapping on mosiac. 
![image](https://cloud.githubusercontent.com/assets/12292333/24072928/f24ad2da-0bee-11e7-8e4a-bc3ce5223f7e.png)

**Comment by mstreit** [comment]
But what happens when the vis is already switched **before** brushing? Please push your current state so that I can test it myself.

**Comment by mstreit** [comment]
Do you remove/merge the splitted multiforms again after the user changes the brush? Or what is your plan regarding this?

**Comment by bikramkawan** [comment]
Currently, It removes. I can perform single instance only.I plan to extend for multiple brushing by keeping previously brushed area also.

**Comment by mstreit** [comment]
OK, removing sounds good. Single brush is also fine at the moment. We should try to get the minimum features done before improving the ones we have.

**Comment by bikramkawan** [comment]
I have kept down here two solutions based on the new layout.
![2017-03-21_10-37-51](https://cloud.githubusercontent.com/assets/12292333/24142007/8b070268-0e25-11e7-9764-a438728383eb.png)

FYI the box represent one multiform currently stratified by career status

Case A: We increase the height of the brushed element and squeeze other elements but never increase the total height of multiform. In this scenario, the row height of unfocused will be unequal to the row height to the another multiform( other stratification).

Case B:
We increase the total height of multiform after applying brushing and assign the more height for the brushed area but the height of other elements will stay the same as before. The more height required for multiform will be compensated from other multiforms(stratification).In this scenario, the row height of unfocused will be equal to the row height to the another multiform (other stratification).

**Comment by bikramkawan** [comment]
![2017-03-21_13-00-43](https://cloud.githubusercontent.com/assets/12292333/24146573/8a747eaa-0e36-11e7-8eee-7377ac48d527.gif)
Current State: There is some issue remaining:
The speed of rendering and brushing is incorrect. If we brush very fast there is lag as you can see here.
