### ISSUE TITLE
Remove non feasible visualizations from toolbar

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#56]
The user should only be able to switch to meaningful other visualizations that make sense for the data type. 
![image](https://cloud.githubusercontent.com/assets/12292333/22695320/a9d819da-ed4a-11e6-980b-8164efec7b5b.png)

**Comment by thinkh** [comment]
I think that can be part of the "magic box". We should only show visualizations that are explicitly defined in that "magic box".
@katush Is there a ticket for the "magic box"?

**Comment by mstreit** [comment]
related to #212

**Comment by mstreit** [comment]
The list of possible visualizations for the different data types is defined here:
https://docs.google.com/spreadsheets/d/1q9XLe2LacuuQYAaJ_ewj51do-UX_AhmeZHF8YEoS_6g/edit#gid=0

**Comment by katush** [comment]
addressed by this https://github.com/Caleydo/mothertable/commit/1c92807cad41ae1c7c97562fb1ff5f1a7230321d
