### ISSUE TITLE
Add color coding in TCGA categorical data

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#57]
Color coding is missing in TCGA data for categorical data

**Comment by mstreit** [comment]
@bikramkawan, please take care of this issue soon. It's important for testing.

![image](https://cloud.githubusercontent.com/assets/4129755/23170767/bc387622-f850-11e6-8093-12bcfde6a18e.png)

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23217103/72e2d2b0-f918-11e6-904a-4cf22b3e4ba0.png)
Please first update your phovea_data_hdf from the develop branch.
