### ISSUE TITLE
Let user change column width interactively

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#58]
The user should be able to resize the width of the column by some icon on the header or by dragging left or right as in lineup.

**Comment by mstreit** [comment]
@mijar, are you working on this or can @thinkh take over the issue?

**Comment by mstreit** [comment]
Is #106 a duplicate of this issue?

**Comment by thinkh** [comment]
Yes. The #106 seems to be more specific, so I would use that as reference and close this.
