### ISSUE TITLE
Universal resize layout icon

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#61]
There should be a universal resize icon somewhere. If it is activated all the columns will update layout to fill the available space.

**Comment by mstreit** [comment]
Why do we need such an icon? If possible, our table vis should decide if the space is needed.

**Comment by mstreit** [comment]
@bikramkawan, please follow up to ongoing discussions.

**Comment by bikramkawan** [comment]
It was my thought for the following scenario.
1. User increased the space of the column beyond the requirement.
2.The user continues to this same action for more columns.
3.When we add new column, we might be lost some space from those expanded columns.
4. So to auto adjust all the column with sufficient width there could be some universal resize button.

**Comment by mstreit** [comment]
OK, but cannot the layout manager decides to do this? If we have too little space, we need to shrink and/or aggregate columns.

**Comment by bikramkawan** [comment]
Yes, it should be somewhere in layout manager which can be performed dynamically or else explicitly from some button.

**Comment by mstreit** [comment]
@mijar, do you think we need an explicit button for this or can the layout manager handle this without bothering the user?

**Comment by mstreit** [comment]
@mijar ping!

**Comment by mijar** [comment]
oh sorry, I missed this one. I think that so far it is quite good when leaving it up to the manager...maybe after we will see how it behaves on some real scenario when the BI guys will be ble to play with it, my thoughts will change.:-)

**Comment by mstreit** [comment]
OK, then let's close it for now.
