### ISSUE TITLE
Layout behavior

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#62]
- [x] When content is smaller than screen size - Specify max width and height for visualization

- [x] When content reaches the screen size - allow shrinking to the lowest possible level (specify min width and height)

- [x] If content cannot fit anymore - allow scrolling or apply aggregation

**Comment by mstreit** [comment]
@think, this is done, right?

**Comment by thinkh** [comment]
Yes, everything from the list is done. Therefore I close the issue.
