### ISSUE TITLE
Create tooltip to display  additional information

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#64]
When hover over the cell it should display additional information.
Such as counts for categorical, value for numerical.
![image](https://cloud.githubusercontent.com/assets/12292333/22696516/8a1c6412-ed4e-11e6-8c1f-a0508918df24.png)

**Comment by mstreit** [comment]
yes, but only if there is not enough space to show the labels. If we have the space, we can show the text.

**Comment by mstreit** [comment]
For heatmap we already have a tooltip. Please also add to barchart so that we can close this issue.

**Comment by bikramkawan** [comment]
I have added tooltip I think should be addressed by #43

**Comment by mstreit** [comment]
Works now for barchart. Thanks @bikramkawan.
