### ISSUE TITLE
Create circle renderer for numerical data

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#66]
![image](https://cloud.githubusercontent.com/assets/12292333/22697140/e1f738a4-ed50-11e6-93e9-fed752ba929b.png)

**Comment by mstreit** [comment]
Prop symbol vis already implemented in this branch:https://github.com/phovea/phovea_vis/commit/3671a514a6a6cbafc2168ca2a3f45905eee78185
@sgratzl, can you make a PR for this?

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23947085/729b4eac-097d-11e7-985c-e074c99493c8.png)
There are many conflicts regarding boxplot, list and other stuff on phovea vis in order to  get updates from https://github.com/phovea/phovea_vis/commit/3671a514a6a6cbafc2168ca2a3f45905eee78185
@katush Could you please try to resolve conflicts?

**Comment by mstreit** [comment]
@katush, this is supposed to work now, right?
