### ISSUE TITLE
Resize multiform on update

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#68]
The default size for the multiform area is not specified. When we switch from one visualization to another the scaling of SVG is not correct.
The width of SVG is small to render the boxplot.
![image](https://cloud.githubusercontent.com/assets/12292333/22697415/aa263172-ed51-11e6-9c74-a3a609c3dfe2.png)

**Comment by mstreit** [comment]
@bikramkawan @katush, is this still an issue?

**Comment by thinkh** [comment]
This is fixed.
