### ISSUE TITLE
create missing visualizations

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/mothertable#7]
* circle visualization similar to bar plot 
 * circle visualization showing an aggregated version (e.g. mean)
 * single heatmap cell visualization (e.g. mean)

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/22696725/70efc30c-ed4f-11e6-8a72-05d7f5c4e009.png)

**Comment by mstreit** [comment]
@bikramkawan, please extract the specific visualization to separate issues and close this one.

**Comment by bikramkawan** [comment]
ok
