### ISSUE TITLE
Keep filter view when removing the column if it is part of filter.

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#77]
There is already some filter applied. Now when we try to add new categorical data the color should be faded if it has some data filtered out.
![image](https://cloud.githubusercontent.com/assets/12292333/22775444/0c7efec0-eeac-11e6-94b7-dfd3e5925e4e.png)
Here artist from Barbados and Ireland are already filtered out. So when we add this attribute the color should be faded.

**Comment by mijar** [comment]
rewrite the functionality as we discussed now, thanks ;)

**Comment by bikramkawan** [comment]
Scenario:

1. Add Artists.
2.Add Origin.
3.Add gender.
4.Apply filter on Origin and Gender.
5.Remove Origin column from the main view.
6.The filter view of Origin is also removed (Current State).

TODO: Do not remove from the filter view if it is part of filtering some data only remove a column from the main view.

**Comment by mstreit** [comment]
Yes. If the filter element receives a remove event, it needs to check whether the user actively set a filter. If this is the case, just ignore the event and do nothing.
