### ISSUE TITLE
Apply filter if we select attributes from another idtype

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#78]
![image](https://cloud.githubusercontent.com/assets/12292333/22775786/795a6b28-eead-11e6-80d2-62b27cf851f6.png)

**Comment by bikramkawan** [comment]
Combine filter combination from artist and country

**Comment by bikramkawan** [comment]
Still more scenario needs to be tested for the different combination.

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/22825250/604eaeca-ef8c-11e6-83a7-108f3ee65db6.png)

If we select any attributes from another idtype just update matrix in the column direction. The row direction should be unaffected.

**Comment by mijar** [comment]
1. Artists - add label, Origin, Career Status, Number1Hits
2. Countries - add Continents, Population...
3. Do some filtering on both attributes from Countries...some of the columns disappear

**Comment by bikramkawan** [comment]
I think this is fine right ? @mijar

**Comment by mijar** [comment]
I tested it and I think it is related only to the implementation of numerical filter and its boundary values - that it is currently hard to include them again. Was the #35 about this or not?

**Comment by bikramkawan** [comment]
Yes

**Comment by mijar** [comment]
ok then I'm closing this one.
