### ISSUE TITLE
Add transition before updating main view

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#81]
Assume some data are filtered out. Do not update the main view directly. There should be some animation or transitional phase to update the main view.

**Comment by mstreit** [comment]
Grey out filtered elements during filter drag operation. Filtered elements should be removed after user drops the filter.

**Comment by mstreit** [comment]
I suggest to use a similar approach as we used for encoding rank changes in Lineup. If a group switches from aggregated to non aggregated mode (or vice versa) we can change the background color and slowly fade it back to white. 

Transition steps:
- Remove current multiform vis
- Change background color
- Animated transition of group cell
- Add new multiform vis
- Fade out background highlight color (back to white)
