### ISSUE TITLE
Create Filter Block

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#9]
It consists block which will be useful for changing the main view on changing the selection.

![image](https://cloud.githubusercontent.com/assets/12292333/22255977/84c70b0c-e259-11e6-8905-e4a39e5ec68f.png)

**Comment by mstreit** [comment]
Looks like this is done, right?

**Comment by bikramkawan** [comment]
Yes . It supports for string, numerical, categorical and matrix for now.

**Comment by mstreit** [comment]
OK, then please close the ticket and create more specific ones for missing sub-features or extensions.

**Comment by bikramkawan** [comment]
See here
https://github.com/Caleydo/mothertable/commit/7c486b8c74e8d4fb37b10aebe1b2d95420ca14c2
