### ISSUE TITLE
String column adjustment

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#93]
The string column is wrongly adjusted.
![image](https://cloud.githubusercontent.com/assets/12292333/22978555/7b9e5efe-f393-11e6-81e1-9cf304017547.png)

**Comment by mstreit** [comment]
@katush, how is it going with the resizing? Any particular problems for which you could use some help?

**Comment by katush** [comment]
It now works for string and bar columns.
![resizing](https://cloud.githubusercontent.com/assets/8986080/23030819/34bf6550-f46f-11e6-8a4d-683e910cce75.png)

**Comment by mstreit** [comment]
very nice!

**Comment by mstreit** [comment]
Let's switch to the actual StringVector visualization.
@thinkh, could you please take care of this?

**Comment by thinkh** [comment]
@katush It doesn't work in my local environment. What is the to do here?

**Comment by thinkh** [comment]
This is what I see in the master branch. 

![taggle_vectorstring](https://cloud.githubusercontent.com/assets/5851088/23624631/aeff435e-02a6-11e7-87c8-704d4eb83c58.png)

@katush How can I reproduce the state you showed above?

**Comment by sgratzl** [comment]
can you switch from the table vis to the list vis, please?

**Comment by mstreit** [comment]
Looks much better. 
![image](https://cloud.githubusercontent.com/assets/4129755/23657567/0cbcb330-033f-11e7-9a0c-a33573882fb0.png)

Can we please add some padding before the label on the left? Then we can close this issue.

**Comment by thinkh** [comment]
Fixed. 

![taggle_string-list-spacing](https://cloud.githubusercontent.com/assets/5851088/23658168/bf1a91e4-0341-11e7-861d-f6706c1cd0fe.png)
