### ISSUE TITLE
Preview of how much data we see from the whole dataset of particular ID type, in filter view

### ISSUE THREAD

**Issue by mijar** [Caleydo/mothertable#94]
Extension of the filter view - put a bar beneath the IDtype combobox showing ratio of currently seen data to the whole dataset. The color can be some normal one :-) or the bar can be just black and the filtered part can become grey.

![image](https://cloud.githubusercontent.com/assets/7511570/22985010/7767a8ae-f3a7-11e6-89c7-4ed616bdd047.png)

**Comment by bikramkawan** [comment]
Is this the brown bar beneath the countries you mean.

**Comment by mstreit** [comment]
yes

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/22994637/ee1675aa-f3c7-11e6-8b95-b21013d8c005.png)
